// Project type templates — each entry defines phases with their checklist items.
// Each phase has a name and an array of requirement strings (fully editable after creation).

export const PROJECT_TYPE_CATALOG = [
  {
    category: 'Fire Alarm',
    icon: '🔥',
    types: [
      { value: 'fire_alarm_new_construction', label: 'New Construction (Ground-Up)', description: 'Full building from dirt — multi-story concrete/steel frame' },
      { value: 'fire_alarm_tenant_improvement', label: 'Tenant Improvement', description: 'TI work in existing shell or occupied building' },
      { value: 'fire_alarm_retrofit', label: 'Retrofit / Replacement (Occupied)', description: 'Old system removed, new system installed while building is occupied' },
      { value: 'fire_alarm_service_inspection', label: 'Service & Inspection (ITM)', description: 'Annual/semi-annual inspection, testing & maintenance — NFPA 72 compliance' },
      { value: 'fire_alarm_special_hazard', label: 'Special Hazard / Suppression', description: 'Clean agent, CO2, foam, or kitchen suppression systems' },
    ]
  },
  {
    category: 'Low Voltage',
    icon: '📡',
    types: [
      { value: 'low_voltage_structured_cabling', label: 'Structured Cabling', description: 'Cat6/fiber backbone, IDF/MDF, patch panels' },
      { value: 'low_voltage_access_control', label: 'Access Control', description: 'Card readers, electric strikes, door hardware' },
      { value: 'low_voltage_cctv', label: 'CCTV / Video Surveillance', description: 'IP cameras, NVR/DVR, monitoring systems' },
      { value: 'low_voltage_av', label: 'Audio / Visual', description: 'Conference rooms, digital signage, sound systems' },
      { value: 'low_voltage_nurse_call', label: 'Nurse Call', description: 'Healthcare nurse call and emergency systems' },
    ]
  },
  {
    category: 'ISP / Telecom',
    icon: '🌐',
    types: [
      { value: 'isp_fiber_backbone', label: 'Fiber Backbone', description: 'Aerial/underground fiber runs, splice, termination' },
      { value: 'isp_wireless', label: 'Wireless Infrastructure', description: 'WAPs, antennas, outdoor wireless links' },
      { value: 'isp_underground', label: 'Underground Conduit', description: 'Boring, trenching, conduit, pull boxes' },
    ]
  },
  {
    category: 'General Construction',
    icon: '🏗️',
    types: [
      { value: 'residential', label: 'Residential', description: 'Single family, multifamily, renovation' },
      { value: 'commercial', label: 'Commercial', description: 'Office, retail, hospitality' },
      { value: 'industrial', label: 'Industrial', description: 'Warehouse, manufacturing, data center' },
      { value: 'infrastructure', label: 'Infrastructure', description: 'Roads, utilities, civil' },
      { value: 'renovation', label: 'Renovation / TI', description: 'General renovation or tenant improvement' },
    ]
  },
];

// ─── PHASE TEMPLATES ──────────────────────────────────────────────────────────

export const PHASE_TEMPLATES = {

  // ─── FIRE ALARM: NEW CONSTRUCTION ─────────────────────────────────────────
  fire_alarm_new_construction: [
    {
      phase: 'Bidding & Estimating',
      items: [
        'Download architectural and MEP sets (structural, electrical, mechanical)',
        'Perform quantity takeoff by floor: smoke detectors (count per room/corridor)',
        'Count heat detectors (kitchens, mechanical rooms, elevator shafts)',
        'Count duct detectors (AHUs over 2000 CFM)',
        'Count pull stations (egress paths, max travel distance 200ft)',
        'Count horn/strobes (sleeping vs. non-sleeping areas)',
        'Count speaker/strobes (voice evac buildings)',
        'Count monitor modules (sprinkler flow/tamper, elevator status)',
        'Count control modules (fan shutdown, door holders)',
        'Count annunciators (main entry + fire command center)',
        'Size FACP with expansion cabinets',
        'Count remote power supplies (NAC extenders)',
        'Calculate SLC loop wire: 18/2 shielded (linear feet per floor)',
        'Calculate NAC wire: 14/2 or 12/2 (based on voltage drop)',
        'Calculate speaker wire: 18/2 (for voice evac)',
        'Calculate risers: pairs per floor',
        'Get manufacturer list pricing (Honeywell/Siemens/Edwards/Simplex)',
        'Apply distributor discount (typically 30-50% off list)',
        'Add markup for client (typically 15-25%)',
        'Estimate labor hours per device (0.5-2 hrs depending on ceiling height)',
        'Estimate hours per 1000ft wire pull (2-4 hours per run)',
        'Estimate programming hours (1-2 hours per 100 devices)',
        'Estimate engineering hours (shop drawings + as-builts)',
        'Obtain 3 subcontractor bids (if using alarm sub)',
        'Verify subcontractor license and insurance',
        'Check manufacturer certifications for subs',
      ]
    },
    {
      phase: 'Material Procurement & Inventory',
      items: [
        'Create bill of materials organized by floor/wing',
        'Separate BOM: device type, rough-in materials (boxes/conduit/strut), trim materials',
        'Order long lead items first: FACP (4-8 weeks)',
        'Order annunciators (same lead time as panel)',
        'Order special finishes (brass/stainless covers) early',
        'Set up inventory tracking system',
        'Establish receiving inspection process for damaged goods',
        'Set up staging area in trailer or secured room',
        'Implement check-out system for technicians',
        'Set up return process for unused material',
        'Confirm primary distributor (stocking)',
        'Identify backup supplier for shortages',
        'Arrange drop-ship to job site where possible',
      ]
    },
    {
      phase: 'Pre-Construction & Coordination',
      items: [
        'Attend BIM coordination meetings',
        'Clash detection with ductwork, pipe, steel',
        'Adjust device locations as needed from coordination',
        'Get signed-off coordination drawings',
        'Submit shop drawings to engineer: riser diagram',
        'Submit floor plans with device addresses',
        'Submit panel elevation and conduit entry drawings',
        'Submit voltage drop calculations',
        'Submit battery capacity calculations',
        'Submit cut sheets for all equipment',
        'Get approved submittals stamped and returned',
        'Apply for fire alarm permit: submit stamped drawings',
        'Pay permit fees',
        'Schedule rough-in inspection with AHJ',
      ]
    },
    {
      phase: 'Concrete & Deck Phase',
      items: [
        'Coordinate box location drawings with electrician',
        'Verify box type (4SQ, 1900, round) and depth (1.5" drywall / 2.125" masonry)',
        'Confirm mounting heights (48" to center typical)',
        'Install boxes on deck before pour (stake to rebar or fasten to deck)',
        'Use zip ties or tie wire to prevent box movement during pour',
        'Install conduit stubs up from boxes',
        'Cap conduits to prevent concrete entry',
        'Mark box locations on deck edge for recovery',
        'Post-pour: locate all boxes',
        'Chip out concrete as needed to find buried boxes',
        'Verify boxes are at correct elevation post-pour',
        'Rod out conduits for concrete debris',
      ]
    },
    {
      phase: 'Rough-In Phase (Above Ceiling)',
      items: [
        'Install support systems: J-hooks or bridle rings for cable tray',
        'Install trapeze supports for larger conduit',
        'Install beam clamps where structural attachment needed',
        'Pull homeruns to riser rooms; label both ends immediately',
        'Leave service loops at devices (18-24")',
        'Leave slack in riser room (10-15ft)',
        'Bundle and tie cables every 8-10ft',
        'Install conduit in exposed areas (parking garages)',
        'Install conduit in plenum areas requiring metal conduit',
        'Install risers between floors',
        'Install conduit in mechanical rooms (subject to damage)',
        'Firestop all penetrations with intumescent putty pads',
        'Install fire caulking at penetrations',
        'Install firestop pillows for larger openings',
        'Document all penetrations with photos',
        'Install SLC loops (verify T-tap policy with manufacturer)',
        'Verify Class A vs Class B wiring per design',
        'Test continuity before drywall',
      ]
    },
    {
      phase: 'Rough-In Inspection',
      items: [
        'Schedule rough-in inspection with AHJ (separate from electrical)',
        'Verify all boxes accessible for inspection',
        'Verify all conduit complete',
        'Verify firestopping visible',
        'Verify wire properly supported',
        'Correct any red tags immediately',
        'Obtain rough-in approval before covering',
      ]
    },
    {
      phase: 'Drywall & Ceiling Phase',
      items: [
        'Coordinate with drywallers: provide mud rings for boxes (1/2" or 5/8" rings)',
        'Ensure boxes are not buried behind board',
        'Mark device locations for cutouts',
        'After drywall: locate all boxes (stud finder if needed)',
        'Cut out drywall at boxes',
        'Install mud rings',
        'Pull wires out of boxes',
        'Coordinate ceiling grid: tile types (lay-in vs. hard lid)',
        'Provide support wires for ceiling-mounted devices',
        'Locate devices relative to grid lines',
      ]
    },
    {
      phase: 'Trim-Out Phase',
      items: [
        'Install device bases: smoke detector bases (twist lock)',
        'Install pull station backplates',
        'Install horn/strobe mounting plates',
        'Wire devices: trim wires to appropriate length, strip and terminate per manufacturer',
        'Use wire nuts or termination blocks; document device addresses on as-built',
        'Install smoke detectors (snap into bases)',
        'Install heat detectors',
        'Install pull stations',
        'Install horns/strobes',
        'Install speakers',
        'Mount FACP backbox to wall at proper height',
        'Pull cables into FACP enclosure',
        'Install batteries in panel',
        'Mount circuit boards',
        'Dress wires with tie wraps and label all field wiring',
      ]
    },
    {
      phase: 'Programming Phase',
      items: [
        'Power up panel: verify primary AC power',
        'Check battery charging voltage',
        'Clear any ground faults before proceeding',
        'Run auto-program (if supported) — let panel discover devices',
        'Verify all devices found vs. installed count',
        'Manual programming: assign custom labels per device (location)',
        'Group devices into zones',
        'Set device types (smoke/heat/pull/duct)',
        'Configure general alarm cause/effect: all devices activate',
        'Configure floor above/below: voice evac zones',
        'Configure elevator recall: lobby detectors trigger recall',
        'Configure HVAC shutdown: duct detectors trigger fans off',
        'Configure door holders: release on alarm',
        'Configure stair pressurization: fans on',
        'Set up central station: phone lines or cellular communicator',
        'Program monitoring account number',
        'Test signal transmission to central station',
        'Confirm receipt with monitoring company',
      ]
    },
    {
      phase: 'Integration Phase',
      items: [
        'Elevator interface: connect to elevator controller',
        'Test elevator primary recall (lobby)',
        'Test elevator alternate recall (alternate floor)',
        'Test shunt trip (machinery room)',
        'HVAC interface: connect to AHU controllers',
        'Test fan shutdown on duct detector alarm',
        'Test stair pressurization fan startup on alarm',
        'Door hardware: connect to magnetic door holders',
        'Test door holder release on alarm',
        'Building automation: provide dry contacts or BACnet interface',
        'Test alarm reporting to BAS',
      ]
    },
    {
      phase: 'Testing & Commissioning',
      items: [
        'Device-by-device test: smoke detectors (aerosol or magnet)',
        'Test heat detectors (heat gun or test mode)',
        'Test duct detectors (test port with magnet)',
        'Test pull stations (physical pull)',
        'Test monitor modules: activate connected device, verify indication',
        'Test control modules: verify controlled equipment operates',
        'Notification testing: measure candela output (visual)',
        'Measure dB levels (audible) — verify 15dB above ambient',
        'Verify synchronized flashing of all strobes',
        'System test: alarm activation from any device',
        'Test trouble conditions (open, ground fault)',
        'Test supervisory conditions (sprinkler valve closed)',
        'Battery backup test (4-24 hours depending on code)',
        'Document all test results: device serial numbers and addresses',
        'Document test dates and results',
        'Mark failed devices for replacement',
      ]
    },
    {
      phase: 'AHJ Final Inspection',
      items: [
        'Schedule with Fire Marshal (often 2-4 weeks out)',
        'Provide approved drawings to inspector',
        'Provide test records',
        'Provide battery calculations',
        'Provide voltage drop calculations',
        'Demonstrate walk test of entire building with AHJ',
        'Demonstrate cause and effect sequences',
        'Demonstrate elevator recall',
        'Demonstrate HVAC shutdown',
        'Demonstrate central station communication',
        'Correct any deficiencies immediately',
        'Obtain certificate of occupancy',
      ]
    },
    {
      phase: 'Closeout & Handover',
      items: [
        'Final as-built documentation: CAD files with device addresses',
        'Produce PDF as-built set for building records',
        'Produce riser diagram with all devices labeled',
        'Produce panel programming report',
        'Compile operations manuals: manufacturer documentation',
        'Write custom operating instructions',
        'Include emergency contact numbers in O&M package',
        'Building engineer training (2-4 hours)',
        'Security staff training (1-2 hours)',
        'Collect training sign-off sheets',
        'Register all equipment for warranty',
        'Provide warranty start date documentation',
        'Schedule 11-month warranty walk',
        'Submit final pay application',
        'Include all change orders in final billing',
        'Collect lien waivers from subs and suppliers',
        'Issue final invoice',
      ]
    },
  ],

  // ─── FIRE ALARM: TENANT IMPROVEMENT (Shell to Suite) ──────────────────────
  fire_alarm_tenant_improvement: [
    {
      phase: 'Bidding & Estimating',
      items: [
        'Site visit: locate existing fire alarm control panel in building',
        'Identify panel manufacturer and model (Simplex, Honeywell, Siemens, Edwards)',
        'Determine if system is addressable or conventional',
        'Check panel capacity for additional devices',
        'Verify building has spare SLC loop capacity',
        'Locate nearest riser access point to tenant space',
        'Check for existing junction boxes in ceiling',
        'Verify ceiling type (grid vs. hard lid)',
        'Takeoff smoke detectors: per code (corridors, common areas)',
        'Takeoff heat detectors: kitchens, boiler rooms',
        'Takeoff pull stations: at exits (max travel distance 200ft)',
        'Takeoff horn/strobes: habitable spaces, corridors',
        'Takeoff speaker/strobes: if building has voice evac',
        'Takeoff monitor modules: tie into tenant sprinkler (if applicable)',
        'Calculate SLC wire (18/2 shielded): run from riser to devices',
        'Calculate NAC wire (14/2 or 16/2): notification circuit',
        'Calculate conduit: homeruns to riser (often required)',
        'Count backboxes: 4SQ or round',
        'Verify all devices match existing manufacturer',
        'Contact building system vendor for programming access',
        'Get programming rate ($150–300/hr typically)',
        'Verify if building requires specific authorized vendor',
        'Obtain compatibility data from base system manufacturer',
        'Estimate device installation labor: 0.75–1.5 hours each',
        'Estimate conduit installation: linear feet at $4–8/ft',
        'Estimate wire pulling: per run + homerun to riser',
        'Estimate termination labor: per device + riser connections',
        'Estimate testing: 0.5 hours per device',
        'Coordinate with electrical contractor for rough-in (if separate scope)',
        'Coordinate drywall patching and ceiling grid installation timing',
      ]
    },
    {
      phase: 'Material Procurement',
      items: [
        'Verify exact model numbers from base system',
        'Order compatible devices from authorized distributor',
        'Allow 2–3 weeks for shipping',
        'Order conduit (EMT or rigid as required)',
        'Order boxes and mud rings',
        'Order mounting hardware',
        'Order fire caulking',
        'Stage materials in tenant space (secured)',
        'Check-in materials upon delivery',
        'Separate by floor/wing if large tenant space',
      ]
    },
    {
      phase: 'Permitting & Approvals',
      items: [
        'Submit shop drawings: floor plan with device locations',
        'Submit riser diagram showing connection to base system',
        'Submit device compatibility letter from manufacturer',
        'Submit cut sheets for all devices',
        'Submit for building owner architectural review',
        'Get property management sign-off',
        'Schedule access to base building panel with building owner',
        'Submit tenant improvement permit application to city',
        'Include fire alarm drawings in permit submittal',
        'Pay permit fees',
        'Schedule inspections with AHJ',
      ]
    },
    {
      phase: 'Rough-In Phase',
      items: [
        'Provide box location plans to electrician',
        'Verify box types and depths with electrician',
        'Confirm mounting heights with electrician',
        'Check for backing requirements (drywall backing)',
        'Install conduit homeruns from tenant space to riser access point',
        'Use minimum 3/4" conduit (typically)',
        'Install pull string in conduit',
        'Cap conduit ends to prevent debris',
        'Support conduit per code',
        'Mount backboxes to studs or backing',
        'Level all boxes',
        'Install mud rings for drywall thickness',
        'Protect boxes from drywall compound',
        'Firestop all conduit entries through rated walls (intumescent putty or caulk)',
        'Document all firestop penetrations with photos',
        'Mark box locations before drywall',
        'Ensure boxes are not buried during drywall installation',
        'Provide cutout locations to drywall crew',
      ]
    },
    {
      phase: 'Riser Connection Preparation',
      items: [
        'Locate base building junction box (electrical room, stairwell, or corridor)',
        'Identify SLC loop in/out wires in junction box',
        'Document existing wiring configuration',
        'Check panel for available addresses',
        'Confirm loop power can handle additional devices',
        'Test existing loop continuity',
        'Determine connection method: T-tap vs. new homerun to panel',
        'Determine if isolator modules are required',
      ]
    },
    {
      phase: 'Wire Pulling & Termination',
      items: [
        'Pull SLC wire from riser junction box to first device',
        'Daisy chain SLC wire between devices',
        'Label both ends of SLC wire with circuit/address info',
        'Leave service loops (12–18" at each device)',
        'Pull NAC wire from riser (or remote power supply) to devices',
        'Follow Class A or B requirements per design',
        'Install EOL resistor at last NAC device',
        'Strip and prepare wires at riser connection',
        'Connect to base building SLC loop at riser',
        'Document connection points for as-built',
        'Label all wires in junction box',
      ]
    },
    {
      phase: 'Trim-Out Phase',
      items: [
        'Install device bases after drywall and paint complete',
        'Mount bases to backboxes and level',
        'Wire devices: trim, strip, and terminate',
        'Document addresses for each device',
        'Install smoke detector heads (snap in)',
        'Install heat detectors',
        'Install pull stations',
        'Install horns/strobes',
        'Install trim plates to cover gaps',
        'Paint trim plates if required to match ceiling',
      ]
    },
    {
      phase: 'Programming & Integration',
      items: [
        'Schedule programming appointment with building vendor',
        'Provide device list with locations to vendor',
        'Provide desired device labels to vendor',
        'Put panel in programming mode',
        'Learn new devices on system',
        'Assign addresses to all new devices',
        'Program custom labels for new devices',
        'Add new NAC circuits to system',
        'Set NAC synchronization',
        'Test NAC output',
        'Verify new devices report to panel',
        'Check for ground faults',
        'Confirm no interference with existing devices',
      ]
    },
    {
      phase: 'Testing Phase',
      items: [
        'Test every smoke detector (aerosol or magnet)',
        'Test every heat detector (heat gun)',
        'Test every pull station (physical pull)',
        'Test every horn/strobe (visual and audible verification)',
        'Measure ambient noise level for sound level testing',
        'Verify notification 15dB above ambient',
        'Document all sound level readings',
        'Verify alarm reports to main panel',
        'Check trouble conditions',
        'Test battery backup if applicable',
      ]
    },
    {
      phase: 'Inspections',
      items: [
        'Schedule rough-in inspection with AHJ (if required)',
        'Verify exposed work visible for rough-in inspection',
        'Verify conduit complete for rough-in inspection',
        'Verify firestopping in place for rough-in inspection',
        'Schedule final inspection with local AHJ',
        'Demonstrate all devices to AHJ',
        'Show communication to base system for AHJ',
        'Provide test records to AHJ',
        'Walk with property manager for building owner acceptance',
        'Demonstrate system operation to property manager',
        'Obtain property manager sign-off',
      ]
    },
    {
      phase: 'Closeout',
      items: [
        'Produce updated floor plans with all device locations (as-built)',
        'Produce device address list',
        'Produce riser diagram showing connection to base system',
        'Provide as-built documentation to building management',
        'Tenant training: demonstrate how to silence alarms',
        'Tenant training: demonstrate how to reset system',
        'Provide emergency contact list to tenant',
        'Submit final invoice',
        'Include all change orders in final billing',
        'Collect lien waiver',
      ]
    },
  ],

  // ─── FIRE ALARM: RETROFIT / REPLACEMENT (Occupied Building) ──────────────
  fire_alarm_retrofit: [
    {
      phase: 'Bidding & Estimating',
      items: [
        'Locate existing FACP (basement, first floor, mechanical room)',
        'Identify existing manufacturer and approximate age',
        'Determine if existing wiring is conduit or cable',
        'Pull ceiling tiles in multiple areas to verify wiring method',
        'Check for abandoned wiring from previous systems',
        'Verify if existing conduit paths are usable',
        'Test existing wire for continuity and insulation condition',
        'Identify all existing device locations (count by type)',
        'Locate all existing annunciators (lobby, front desk, security)',
        'Find all remote power supplies and booster panels',
        'Identify elevator interface location',
        'Locate HVAC shutdown interfaces',
        'Find all door holder power supplies',
        'Check for existing dry contacts to building automation',
        'Verify central station communicator type (phone, cellular, IP)',
        'Photograph every existing device',
        'Photograph existing panel wiring (before touching anything)',
        'Document wire colors and terminations',
        'Create existing device location map (even rough)',
        'Interview building engineers about known issues',
        'Request any existing as-builts from owner',
        'Compare existing system to current code requirements',
        'Identify areas needing additional devices',
        'Check if voice evacuation now required',
        'Verify elevator recall requirements (ASME A17.1)',
        'Check area of refuge requirements',
        'Determine if visible notification required in more areas',
        'Count new devices required (match or exceed existing)',
        'Add code-required devices not in existing system',
        'Calculate SLC devices total',
        'Calculate NAC devices total',
        'Determine panel size required (addressable capacity)',
        'Calculate battery size (standby + alarm)',
        'Count annunciators needed',
        'Identify which existing wiring can be reused',
        'Test existing conduit for obstructions',
        'Check existing backbox sizes (4" vs 4-11/16")',
        'Verify existing device mounting heights meet code',
        'Test existing notification wire gauge (18ga vs 14ga)',
        'Determine floor-by-floor cutover sequence',
        'Identify critical areas (hospital OR, data center, kitchen)',
        'Plan for fire watch during transition',
        'Develop temporary protection requirements',
        'Create communication plan for tenants',
        'Schedule after-hours work windows',
        'Estimate removal labor per device (0.25–0.5 hours)',
        'Estimate new installation labor (often 2x new construction)',
        'Include overtime labor rates (nights/weekends)',
        'Include programming and commissioning hours',
        'Include fire watch staffing costs',
        'Price adapter plates for existing backboxes',
        'Price transition boxes where backboxes cannot be reused',
      ]
    },
    {
      phase: 'Material Procurement & Inventory',
      items: [
        'Order FACP (6–8 weeks typical lead time)',
        'Order annunciators (match panel lead time)',
        'Order remote power supplies',
        'Order cellular communicators',
        'Order adapter plates for existing backboxes',
        'Order universal mounting plates (various manufacturers)',
        'Order box extenders for shallow boxes',
        'Order trim rings for oversized openings',
        'Order SLC wire for new runs',
        'Order NAC wire (14ga minimum typically)',
        'Order speaker wire for voice evac (if applicable)',
        'Establish secure storage area in building',
        'Set up floor-by-floor material carts',
        'Implement daily material pull sheets',
        'Establish evening restocking procedure',
        'Check-in all materials upon delivery',
        'Track serial numbers for panels',
        'Record lot numbers for wire (traceability)',
        'Perform weekly inventory reconciliation',
      ]
    },
    {
      phase: 'Pre-Construction & Permitting',
      items: [
        'Create new riser diagram',
        'Develop floor plans with new device locations',
        'Design phased cutover sequences',
        'Calculate battery and voltage drop',
        'Submit drawings to AHJ including phasing plan',
        'Provide temporary measures documentation',
        'Pay permit fees',
        'Schedule pre-construction meeting with inspector',
        'Present phasing plan to property management',
        'Obtain board approval if condo/HOA',
        'Provide insurance and bonding documentation',
        'Draft tenant notification letters',
        'Post notices in elevators and common areas',
        'Create outage schedule by floor',
        'Establish tenant complaint hotline',
        'Contract with fire watch service',
        'Train building staff on fire watch procedures',
        'Create fire watch routes and checkpoints',
        'Establish radio communication protocol with FD',
      ]
    },
    {
      phase: 'Mobilization & Site Protection',
      items: [
        'Secure storage and technician work area',
        'Set up material receiving zone',
        'Set up waste removal containers',
        'Install dust barriers in work areas',
        'Install floor protection (ram board)',
        'Install elevator protection pads',
        'Stage temporary notification devices',
        'Prepare fire watch radios',
        'Create temporary device location maps',
        'Locate all existing interface points',
        'Document existing connections with photos',
        'Prepare new interface modules',
        'Stage elevator interface hardware',
        'Prepare HVAC shutdown relays',
      ]
    },
    {
      phase: 'Phase 1 – Preparation & Staging',
      items: [
        'Install new riser conduit (if required)',
        'Pull new riser cables',
        'Install new FACP adjacent to old panel',
        'Mount new annunciators adjacent to old',
        'Install new remote power supplies',
        'Install new backboxes where needed',
        'Pull new wire to accessible areas',
        'Install device bases in non-disruptive areas',
        'Label all new wiring',
        'Leave old system fully operational',
        'Pull wire to all new device locations',
        'Terminate at new panel end',
        'Test continuity on all pre-pulled wire',
        'Bench program new panel',
        'Create device database',
        'Program custom labels by floor',
        'Test panel in shop/staging environment',
      ]
    },
    {
      phase: 'Phase 2 – Floor-by-Floor Cutover',
      items: [
        'Notify floor tenants of outage time (day before)',
        'Post notices on floor entrances',
        'Stage materials for floor',
        'Assign technician teams and review floor plan',
        'Verify fire watch coverage is in place',
        'Mobilize technicians after business hours (5:00 PM)',
        'Begin removal of old devices',
        'Document each device removal',
        'Test existing wiring (if reusing)',
        'Install new devices in existing locations',
        'Install additional code-required devices',
        'Pull any missing wire runs',
        'Complete device installation by ~11:00 PM',
        'Begin and complete terminations by ~1:00 AM',
        'Connect to new riser and power up floor devices',
        'Begin and complete device testing by ~4:00 AM',
        'Clean work areas and demobilize by 5:00 AM',
        'Verify floor operational on new system by 6:00 AM',
        'Fire watch patrols every 15–30 min during cutover',
        'Document all fire watch patrol times',
        'Conduct morning walk-through (7:00 AM)',
        'Verify all devices operational post-cutover',
        'Check with tenants for any issues',
        'Document any deficiencies',
      ]
    },
    {
      phase: 'Phase 3 – System Integration',
      items: [
        'Coordinate with elevator vendor for shutdown (night/weekend)',
        'Disconnect old fire alarm elevator interface',
        'Connect new elevator interface modules',
        'Test primary elevator recall',
        'Test alternate elevator recall',
        'Test shunt trip (machinery room)',
        'Document all elevator connections',
        'Return elevators to service',
        'Coordinate with building automation vendor',
        'Identify all AHUs with duct detectors',
        'Disconnect old monitoring modules',
        'Connect new monitor modules for HVAC',
        'Test fan shutdown on alarm',
        'Verify status reporting to BAS',
        'Locate all magnetic door holders',
        'Disconnect old door holder power supplies',
        'Connect to new control modules',
        'Test door holder release on alarm',
        'Install new communicator',
        'Program central station account information',
        'Test signal transmission to central station',
        'Coordinate monitoring switchover date',
        'Maintain old communicator until cutover complete',
        'Verify receipt at central station',
      ]
    },
    {
      phase: 'Phase 4 – Final Panel Cutover',
      items: [
        'Schedule weekend for final panel cutover',
        'Notify central station of switch',
        'Put old panel on test',
        'Transfer all monitoring to new panel',
        'Verify all signals received on new panel',
        'Power down old panel',
        'Remove old panel (or leave per owner request)',
        'Label all old wiring as "abandoned"',
        'Complete all programming on new panel',
        'Verify all devices reporting',
        'Test ground fault detection',
        'Test battery backup',
        'Verify annunciator operation',
        'Test printer if installed',
        'Test random sample of devices (10–20%)',
        'Test alarm from multiple floors',
        'Test trouble conditions',
        'Test supervisory conditions',
        'Verify elevator recall from lobby detectors',
        'Verify HVAC shutdown',
        'Test voice evac messages (if applicable)',
      ]
    },
    {
      phase: 'Testing & Commissioning',
      items: [
        'Test every smoke detector (aerosol)',
        'Test every heat detector (heat gun)',
        'Test every pull station',
        'Test every duct detector',
        'Test every monitor module',
        'Test every control module',
        'Test every notification device',
        'Document all test results',
        'Battery capacity test (full load)',
        'Voltage drop measurements at end of line',
        'Ground fault detection test',
        'AC loss reporting test',
        'Battery trouble reporting test',
        'Communication failure reporting test',
        'Verify general alarm cause/effect',
        'Verify floor above/below notification',
        'Verify elevator recall sequences',
        'Verify HVAC shutdown',
        'Verify door holder release',
        'Verify stair pressurization',
        'Verify area of refuge communication',
      ]
    },
    {
      phase: 'AHJ Final Inspection',
      items: [
        'Schedule final inspection with Fire Marshal',
        'Provide complete building access',
        'Have all test equipment ready',
        'Have all documentation available',
        'Demonstrate random devices to inspector',
        'Show cause and effect sequences',
        'Provide test records',
        'Show battery calculations',
        'Show voltage drop calculations',
        'Provide preliminary as-built drawings',
        'Document all red tags / deficiencies',
        'Schedule immediate correction of deficiencies',
        'Re-inspect as required',
        'Obtain final sign-off',
      ]
    },
    {
      phase: 'Closeout & Handover',
      items: [
        'Complete CAD as-built files with all device addresses',
        'Produce riser diagram with all devices and panels',
        'Produce programming report (device list by address)',
        'Produce cause and effect matrices',
        'Compile wire pull records',
        'Compile test results binder',
        'Compile manufacturer O&M documentation for all equipment',
        'Write custom operating procedures',
        'Prepare emergency contact list',
        'Provide troubleshooting guide',
        'Provide spare parts list',
        'Building engineer training (full system operation)',
        'Security staff training (annunciator operation)',
        'Front desk training (basic troubleshooting)',
        'Provide training videos if possible',
        'Collect training sign-off sheets',
        'Register all equipment for warranty',
        'Provide warranty certificate',
        'Schedule 11-month warranty inspection',
        'Submit final invoice with all approved change orders',
        'Provide lien waivers',
        'Submit release of retainage request',
      ]
    },
  ],

  // ─── FIRE ALARM: INSPECTION, TESTING & MAINTENANCE (ITM) ─────────────────
  fire_alarm_service_inspection: [
    {
      phase: 'Bidding & Estimating',
      items: [
        'Obtain existing system manufacturer and model',
        'Request age of system (years in service)',
        'Ask about recent trouble history',
        'Verify if system is under warranty',
        'Check if client has service records',
        'Determine building occupancy type (impacts test frequency)',
        'Identify number of devices by type (NFPA 72 Table 14.4.2.2)',
        'Site walk: locate FACP and verify operation',
        'Check panel for trouble conditions',
        'Review panel history log (if accessible)',
        'Walk representative floors to verify device types',
        'Identify special hazards (kitchens, elevator rooms, generator)',
        'Check accessibility issues (locked rooms, high ceilings)',
        'Verify central station monitoring status',
        'Document existing deficiencies with photos',
        'Count smoke detectors (area, duct, beam)',
        'Count heat detectors (fixed temp, rate-of-rise)',
        'Count pull stations',
        'Count notification appliances (horns, strobes, speakers)',
        'Count monitor modules (sprinkler flow, tamper)',
        'Count control modules (relays, shutdowns)',
        'Count annunciators and remote power supplies',
        'Count battery banks',
        'Estimate visual inspection time per device (0.05–0.1 hrs)',
        'Estimate functional test time per device (0.1–0.25 hrs)',
        'Estimate panel testing time (2–4 hrs)',
        'Estimate battery testing time (1–2 hrs)',
        'Estimate reporting time (2–4 hrs)',
        'Include travel time (round trip)',
        'Include overtime rates if after-hours required',
        'Determine frequency: annual 100% test, semi-annual battery/panel, quarterly monitoring',
        'Price single visit, annual contract, and multi-year contract options',
        'Develop proposal with NFPA 72 scope, exclusions, schedule, and auto-renewal clause',
      ]
    },
    {
      phase: 'Pre-Inspection Planning',
      items: [
        'Execute signed service agreement and obtain purchase order',
        'Update insurance certificates',
        'Compile contact list (building engineer, security, management)',
        'Coordinate with building management (30+ days notice)',
        'Determine best dates (avoid move-in days, holidays)',
        'Schedule after-hours if required (retail, medical)',
        'Confirm access with security and arrange elevator access',
        'Draft tenant notification letters for building owner',
        'Post notices in elevators and common areas',
        'Specify date, time, expected disruption, and emergency contact number',
        'Call central station 24–48 hours before test',
        'Provide account number(s), test date and time window',
        'Confirm central station will put system on test',
        'Get confirmation number and document who you spoke with',
        'Calibrate test equipment (annual requirement)',
        'Check battery levels in testers',
        'Stock UL-listed aerosol cans and test magnets',
        'Stage replacement parts (batteries, filters)',
        'Load building information into reporting software',
        'Print floor plans and create device count sheets by floor',
        'Gather previous test reports for reference',
        'Prepare deficiency tracking forms and current-year inspection tags',
      ]
    },
    {
      phase: 'Mobilization & Site Access',
      items: [
        'Arrive 15 minutes early',
        'Check in with security/reception and obtain building badges',
        'Contact building engineer',
        'Review site-specific safety requirements',
        'Locate FACP and all remote panels',
        'Check for trouble lights before testing — document existing troubles',
        'Review panel history log (last 30 days)',
        'Verify date and time on panel (correct?)',
        'Check printer paper if applicable',
        'Verify central station communication status',
        'Document panel software version',
        'Brief team: evacuation routes, emergency exits, first aid kit location',
        'Establish communication method (radios, phones)',
        'Review ladder safety if applicable',
      ]
    },
    {
      phase: 'Visual Inspection',
      items: [
        'Inspect FACP: physical damage, circuit boards seated, wiring, corrosion/moisture',
        'Inspect batteries for leakage, corrosion, and tight connections',
        'Inspect conduit, raceways, and verify proper circuit labeling',
        'Check each device: physical damage, cleanliness, paint overspray',
        'Verify proper device mounting (secure, not obstructed)',
        'Check for missing trim plates',
        'Document all damaged devices for repair',
        'Elevator machine room: verify devices accessible',
        'Generator room: verify heat detectors present',
        'Kitchen: verify heat detectors (not smoke)',
        'Mechanical rooms: check duct detectors',
        'Data centers: verify pre-action interface',
        'Atrium: verify beam detectors aligned',
        'Notification devices: check strobes for cracks or yellowing',
        'Verify horn/speaker mounting height (80–96" typical)',
        'Verify no obstructions to strobes (ceiling fans, signs)',
      ]
    },
    {
      phase: 'Functional Testing',
      items: [
        'Test AC power loss — verify battery backup activates',
        'Measure battery voltage under load',
        'Test battery charger voltage and current',
        'Test ground fault detection (simulate ground)',
        'Test zone/point disable, system reset, silence, and drill functions',
        'Test printer operation',
        'Smoke detectors: aerosol test (hold 12–18", spray 2–3 sec, verify alarm, reset)',
        'Heat detectors: heat gun or test magnet (fixed temp: verify rating matches)',
        'Pull stations: physical pull, reset with key, verify operation',
        'Duct detectors: test port with magnet, verify fan shutdown, check sampling tubes',
        'Beam detectors: use test filter, verify alignment, check for dirty lens',
        'Strobes: verify flash (candela rating), measure with light meter if required',
        'Horns: measure dB level (15dB above ambient) at farthest point',
        'Speakers: verify voice message clarity, test tone and voice modes',
        'Verify synchronization of all strobes',
        'Sprinkler flow switch: open test valve, verify alarm within 90 seconds',
        'Sprinkler tamper switch: simulate supervisory signal',
        'Fan shutdown: verify AHU stops, confirm with building engineer',
        'Door holders: verify release and doors close',
        'Elevator recall: simulate lobby detector, verify elevators return to designated floor',
        'Annunciator: verify all LEDs, test buttons (acknowledge, silence, reset), check LCD',
        'Test alarm, trouble, supervisory, and restoral signals to central station',
        'Confirm central station receives all signals correctly',
      ]
    },
    {
      phase: 'Battery Testing',
      items: [
        'Check battery date code (replace every 4–5 years)',
        'Inspect for corrosion, swelling, or leakage',
        'Verify terminal connections are tight',
        'Check interconnecting cables',
        'Measure voltage without load',
        'Apply load (alarm condition) and measure voltage after 1 minute',
        'Calculate capacity and compare to manufacturer specifications',
        'Document all battery test results',
        'Verify charging voltage within spec (13.6–13.8V for 12V systems)',
        'Verify automatic transfer to float charging mode',
      ]
    },
    {
      phase: 'Documentation & Reporting',
      items: [
        'Record each device test result (pass/fail) with location and address',
        'Photograph all failed devices',
        'Apply red tag to failed devices: note reason, date, and initial',
        'Photograph all tagged devices',
        'Provide deficiency tag copy to building engineer',
        'Generate test report: device summary, pass/fail stats, deficiency list',
        'Include battery and panel function test results in report',
        'Include communication test verification',
        'Include photos of all deficiencies',
        'Include NFPA 72 compliance statement',
        'Apply current-year inspection tag to panel and remote annunciators',
      ]
    },
    {
      phase: 'Post-Inspection & System Restoration',
      items: [
        'Return system to normal — clear all test conditions',
        'Verify no troubles remain after restoration',
        'Verify central station receives restoral signal',
        'Meet with building engineer to review deficiencies found',
        'Discuss urgent repairs and provide preliminary report',
        'Schedule follow-up for repairs',
        'Call monitoring company to confirm test complete',
        'Confirm system is back in service',
        'Document all call details',
      ]
    },
    {
      phase: 'Repair Follow-Up',
      items: [
        'Itemize each failed device with replacement pricing (labor + materials)',
        'Note urgency for each deficiency (life safety vs. minor)',
        'Submit repair quotation within 48 hours of inspection',
        'Coordinate building access for repair visit',
        'Order replacement parts',
        'Schedule technician visit and notify tenants if disruption expected',
        'Test all replaced devices after repair',
        'Update test records',
        'Provide completion report and update inspection tags',
      ]
    },
    {
      phase: 'Invoicing & Closeout',
      items: [
        'Submit final invoice (inspection fee + any approved repairs)',
        'Attach test report to invoice',
        'Include purchase order reference',
        'Store test reports digitally and physically',
        'Update client database with next inspection due date',
        'Note any recurring issues for future reference',
        'Schedule next inspection in system',
        'Set 30-day follow-up reminder for open repairs',
        'Follow-up call within one week to verify no new issues',
        'Ask for referral opportunities',
        'Document client feedback',
      ]
    },
  ],

  // ─── LOW VOLTAGE: STRUCTURED CABLING (New Construction) ──────────────────
  low_voltage_structured_cabling: [
    {
      phase: 'Bidding & Estimating',
      items: [
        'Download architectural drawings (floor plans, reflected ceiling plans)',
        'Obtain electrical drawings (power outlet locations)',
        'Review telecommunications drawings (if available)',
        'Identify MDF and IDF room locations',
        'Note building type (concrete, steel stud, wood frame)',
        'Identify ceiling type (lay-in tile, hard lid, open plenum)',
        'Check for existing conduit or pathways',
        'Review TIA/EIA standards applicable (568-C, 569, 606, 607)',
        'Count workstation outlets (data/voice) per square footage',
        'Identify ceiling mount access point (WiFi) locations',
        'Identify camera locations (if part of scope)',
        'Calculate backbone fiber requirements (riser count)',
        'Determine voice pairs (if analog phones)',
        'Size patch panels (24 or 48 port) by IDF',
        'Calculate cable management needs (horizontal and vertical)',
        'Size racks and cabinets (by IDF)',
        'List fiber enclosures and splice trays',
        'Calculate copper cabling boxes (1000ft) by run count',
        'Determine average run length (add 20% for slack/waste)',
        'Classify cable types (plenum vs. riser vs. general purpose)',
        'Confirm category rating (6, 6A, 8) based on client needs',
        'Quantify J-hooks or bridle rings (spacing 4-5 ft)',
        'Measure cable tray (ladder rack) linear feet needed',
        'Calculate innerduct (for fiber) linear feet',
        'Determine conduit sizes and lengths',
        'Count pull boxes and junction boxes',
        'Estimate firestop materials (putty, caulk, pillows)',
        'Calculate support hardware (beam clamps, threaded rod, trapeze)',
        'Quantify ladder rack overhead per telecom room',
        'Measure backboard requirements (3/4" AC plywood)',
        'List grounding bus bar and conductors (#6 AWG minimum)',
        'Calculate receptacle needs (dedicated circuits per rack)',
        'Verify lighting (minimum 50 foot-candles)',
        'Review HVAC requirements (cooling calculations)',
        'Estimate pathway installation labor (hours per foot)',
        'Estimate cable pulling labor (2-4 hours per 1000ft box)',
        'Estimate termination labor (0.25-0.5 hours per cable)',
        'Estimate testing labor (0.1-0.2 hours per cable)',
        'Estimate labeling labor (0.05 hours per cable/port)',
        'Estimate rack build-out labor (4-8 hours per rack)',
        'Include project management hours (10-15% of labor)',
        'Include engineering hours (shop drawings, submittals)',
        'Obtain vendor quotes for copper cable (bulk pricing)',
        'Obtain fiber cable quotes (single-mode vs. multi-mode)',
        'Quote connectors and jacks (bulk pricing)',
        'Quote patch panels (load with keystone jacks)',
        'Quote racks and accessories',
        'Quote firestop materials',
        'Calculate test equipment rental (if not owned)',
        'Obtain electrical subcontractor quote (conduit)',
        'Obtain drywall patching quote (if cutting in boxes)',
        'Obtain ceiling tile replacement quote (if damaged)',
        'Obtain painting quote (if conduit exposed)',
        'Obtain firestop specialist quote (if complex)',
        'Calculate material markup (15-25%)',
        'Calculate labor markup (20-30%)',
        'Include bond and insurance (2-3%)',
        'Add general conditions (5-10%)',
        'Add profit margin (8-15%)',
        'Add contingency reserve (5-10%)',
      ]
    },
    {
      phase: 'Material Procurement & Inventory',
      items: [
        'Create bill of materials organized by floor/wing',
        'Organize BOM by rough-in, trim-out, and IDF/MDF materials',
        'Identify long lead items (custom fiber, pre-terminated assemblies)',
        'Note lead times: custom fiber (3-4 weeks), pre-terminated (2-3 weeks)',
        'Note lead times: specialty racks (1-2 weeks), colored jacks (special order)',
        'Select primary cable distributor (stocking)',
        'Select secondary supplier for shortages',
        'Arrange manufacturer direct for large volumes',
        'Identify local suppliers for emergency orders',
        'Release rough-in materials first (J-hooks, tray, conduit)',
        'Release cable after pathways approved',
        'Stage termination materials for later delivery',
        'Confirm ship dates weekly',
        'Check packing slips against purchase orders on receipt',
        'Inspect for damage (crushed boxes, cut reels)',
        'Verify cable type and length on reels',
        'Test sample reels (if required)',
        'Document shortages immediately',
        'Set up secured staging area for materials',
        'Log materials in (date received, quantity)',
        'Issue materials to technicians (check-out)',
        'Track cable usage (feet pulled vs. feet received)',
        'Perform weekly inventory reconciliation',
        'Return unused material to stock',
        'Organize job site storage (locked conex box or room)',
        'Install cable reel racks (vertical spindles)',
        'Prepare material carts for each floor',
        'Daily material pulls organized by task',
      ]
    },
    {
      phase: 'Pre-Construction & Coordination',
      items: [
        'Create floor plans with outlet locations',
        'Show pathway routing (cable tray, J-hooks) on plans',
        'Develop rack elevations for each IDF',
        'Create riser diagram (backbone fiber/copper)',
        'Develop TIA-606-B compliant labeling scheme',
        'Create firestop detail drawings',
        'Create grounding detail drawings',
        'Compile cut sheets for all materials',
        'Include manufacturer spec sheets',
        'Add shop drawings to submittal',
        'Submit to engineer/architect',
        'Track submittal status',
        'Incorporate architect comments',
        'Obtain approved submittals',
        'Attend BIM coordination meetings (if applicable)',
        'Model cable tray and major pathways in BIM',
        'Check clashes with ductwork (HVAC)',
        'Check clashes with piping (plumbing, fire sprinkler)',
        'Check clashes with structural steel',
        'Check clashes with light fixtures',
        'Check clashes with ceiling grid',
        'Adjust routing to resolve clashes',
        'Get signed-off coordination drawings',
        'Check if low voltage permit required',
        'Submit drawings to AHJ (if required)',
        'Pay permit fees',
        'Schedule inspections with AHJ',
        'Attend GC pre-con meeting',
        'Review schedule with construction manager',
        'Coordinate with electrical (power to IDFs, conduit rough-in)',
        'Coordinate with mechanical (cooling for IDFs)',
        'Coordinate with drywall (backbox installation)',
        'Coordinate with ceiling trade (access requirements)',
        'Establish communication protocols',
        'Review safety requirements (site-specific)',
        'Establish testing criteria (Fluke certification levels)',
        'Create inspection checklist',
        'Define acceptable pass/fail thresholds',
        'Plan for re-testing failed runs',
        'Document QC requirements',
      ]
    },
    {
      phase: 'Rough-In: Pathways',
      items: [
        'Coordinate with electrician on box locations',
        'Provide box location drawings to electrical',
        'Verify box type (single-gang, double-gang, 4SQ)',
        'Confirm box depth (2-1/8" minimum for deep devices)',
        'Check mounting heights (18" to center typical data)',
        'Verify backing installed (between studs for wall-mount)',
        'Coordinate conduit stubs to ceiling',
        'Install J-hooks or bridle rings at 4-5 foot spacing',
        'Support within 12" of each box',
        'Support within 24" of each transition',
        'Attach J-hooks to structure (not ceiling grid)',
        'Use beam clamps on steel',
        'Use concrete anchors on slab',
        'Install cable tray sections level and aligned',
        'Install splice plates at tray connections',
        'Bond and ground tray per code',
        'Support tray at 5-8 foot spacing',
        'Install cover plates where required',
        'Install conduit at 10-foot support spacing',
        'Install pull boxes at bends and long runs',
        'Ream all conduit ends to prevent cable damage',
        'Install pull string in conduit',
        'Cap conduit ends to prevent debris entry',
        'Install backboxes per approved drawings',
        'Mount backboxes to studs or backing',
        'Level and secure all backboxes',
        'Install mud rings for drywall thickness',
        'Protect backboxes from drywall compound (tape over)',
        'Install firestop around all penetrations',
        'Apply intumescent putty to through-rated walls',
        'Apply firestop pillows or caulk to floor penetrations',
        'Document firestopping with photos before covering',
        'Schedule rough-in inspection with GC/AHJ',
        'Verify all supports installed',
        'Check pathway capacity (not overfilled)',
        'Confirm firestopping complete',
        'Get approval before concealing work',
      ]
    },
    {
      phase: 'Rough-In: Cable Pulling',
      items: [
        'Verify all pathways complete before pulling',
        'Confirm boxes installed and accessible',
        'Label all cables before pulling (flag method)',
        'Plan pull sequences (home run to IDF)',
        'Assign technician teams (feeders and pullers)',
        'Position cable reels at feed point',
        'Use reel jacks or spindles for stability',
        'Measure and cut cable lengths (add 10-15% slack)',
        'Bundle cables by destination area',
        'Maintain proper pulling tension (25 lbs max for Cat6)',
        'No kinking or sharp bends (4x cable diameter)',
        'Use lubricant for long/conduit pulls',
        'Pull in groups (4-6 cables per pull)',
        'Do not exceed cable bend radius',
        'Avoid crossing or tangling cables',
        'Lay cables neatly in J-hooks/tray',
        'Prevent crushing from other trades',
        'Separate from power (maintain separation)',
        'Cross power at 90 degrees only',
        'Leave slack coils at each box (18-24")',
        'Leave slack in IDF room (10-15 ft)',
        'Apply temporary labels at both ends',
        'Match cable ID to outlet ID on labels',
        'Document cable runs on pull sheets',
        'Update as-built documentation in real-time',
        'Remove excess cable scraps',
        'Neaten bundles in pathway',
        'Cap unused conduit openings',
        'Protect exposed cables from damage',
      ]
    },
    {
      phase: 'Rough-In: Fiber Backbone',
      items: [
        'Confirm innerduct installed (or dedicated conduit)',
        'Verify no sharp edges in fiber pathway',
        'Check bend radius (20x cable diameter)',
        'Install pull rope (mule tape) in pathway',
        'Use tension monitoring for long runs',
        'Follow manufacturer pulling tension specs',
        'No kinking (fiber is glass)',
        'Use swivel pulling eye',
        'Lubricate with fiber-safe lubricant as needed',
        'Pull continuously (no stopping mid-pull)',
        'Leave slack loops in IDF/MDF (minimum 30 ft)',
        'Coil fiber properly (maintain bend radius)',
        'Store in cable management or overhead',
        'Protect fiber ends with caps',
        'Record fiber cable type (SM/MM, strand count)',
        'Note total length pulled',
        'Document path taken (riser, tray, conduit)',
        'Label both fiber ends',
      ]
    },
    {
      phase: 'Drywall & Ceiling Coordination',
      items: [
        'Conduct pre-drywall walk',
        'Verify all boxes installed correctly',
        'Check for boxes that will be buried',
        'Confirm cables pulled to boxes',
        'Coil cables inside boxes for protection',
        'Photograph all concealed work',
        'Coordinate with drywall crew during installation',
        'Provide mud rings for correct wall thickness',
        'Ensure boxes not covered by drywall',
        'Check cutouts at device locations',
        'Locate all boxes after drywall (stud finder if needed)',
        'Cut out drywall at box locations',
        'Install mud rings',
        'Pull cables out of boxes',
        'Verify cables accessible',
        'Coordinate tile types (lay-in vs. hard lid)',
        'Ensure access panels near termination points',
        'Verify ceiling-mounted device locations',
        'Check for interference with ceiling grid',
      ]
    },
    {
      phase: 'Trim-Out: Termination',
      items: [
        'Install backboard or plywood in IDF/MDF',
        'Paint backboard (white or light color)',
        'Install ladder rack',
        'Mount equipment racks',
        'Install grounding bus bar',
        'Run grounding conductors (to building ground)',
        'Coordinate with electrician for receptacles',
        'Dress cables into racks',
        'Use velcro ties (no zip ties on cables)',
        'Maintain bend radius at patch panels',
        'Leave service loops for re-termination',
        'Bundle cables by floor/wing',
        'Strip cable jacket (proper length, no nicks)',
        'Untwist pairs (minimum necessary)',
        'Maintain pair twists to within 1/2"',
        'Terminate to T568A or B (consistent standard)',
        'Punch down with impact tool',
        'Trim excess wires',
        'Install dust covers on open ports',
        'Terminate workstation jacks per same standard',
        'Seat jack into faceplate',
        'Install faceplate on box',
        'Label faceplate with outlet ID',
        'Tighten faceplate screws securely',
        'Strip fiber buffer tube and strength members',
        'Clean fibers with alcohol wipes',
        'Cleave and splice or connectorize fibers',
        'Test each termination (microscope for cleanliness)',
        'Store splices in splice tray',
        'Install in fiber enclosure',
        'Label fiber ports',
        'Route pre-terminated fiber connectors carefully',
        'Install into adapter panels',
        'Secure excess connector length',
        'Label both ends of fiber runs',
        'Install horizontal cable managers between panels',
        'Install vertical managers at rack ends',
        'Dress and velcro all cables',
        'Ensure no cable stress at termination points',
      ]
    },
    {
      phase: 'Labeling',
      items: [
        'Establish TIA-606-B labeling scheme',
        'Use format floor-room-outlet (e.g., 03-123-A) for workstations',
        'Use format IDF-panel-port (e.g., 2A-01-12) for patch panels',
        'Label both ends of cables matching outlet ID',
        'Assign unique identifier to each rack',
        'Use format source-destination-strand for fiber',
        'Apply self-laminating wrap-around labels (cables)',
        'Apply insert cards to patch panels',
        'Print faceplate labels (laser printer)',
        'Apply rigid plastic labels (racks and cabinets)',
        'Clean surface before applying labels',
        'Apply labels to both ends of each cable',
        'Apply labels to faceplate (visible)',
        'Apply labels to patch panel ports',
        'Apply labels to equipment (routers, switches)',
        'Photograph completed labeling for documentation',
      ]
    },
    {
      phase: 'Testing: Copper',
      items: [
        'Set up Fluke DSX or equivalent test equipment',
        'Calibrate test equipment per manufacturer specs',
        'Select correct test limit (Cat6, Cat6A)',
        'Input cable ID and test parameters',
        'Test wire map (continuity, pairs correct)',
        'Measure length (max 90 meters permanent link)',
        'Measure insertion loss (attenuation)',
        'Measure NEXT (Near-End Crosstalk)',
        'Measure PSNEXT (Power Sum NEXT)',
        'Measure ACR-F (Attenuation to Crosstalk Ratio)',
        'Measure return loss',
        'Measure propagation delay',
        'Measure delay skew',
        'Test 100% of installed cables',
        'Perform permanent link test (no patch cords)',
        'Document test results with cable ID',
        'Mark failures for re-termination',
        'Retest after repairs',
        'Generate PDF test reports',
        'Organize reports by floor/IDF',
        'Include summary of pass/fail statistics',
        'Submit reports to client/GC',
        'Store reports in project folder (digital and print)',
      ]
    },
    {
      phase: 'Testing: Fiber',
      items: [
        'Set up OTDR (Optical Time Domain Reflectometer)',
        'Gather light source and power meter',
        'Obtain launch cables (for OTDR)',
        'Have visual fault locator (red light) available',
        'Measure fiber length with OTDR',
        'Measure attenuation (dB loss) per strand',
        'Measure splice loss (if applicable)',
        'Measure connector loss',
        'Measure reflectance',
        'Measure ORL (Optical Return Loss)',
        'Clean all connectors before testing',
        'Test bi-directionally (both ends)',
        'Test all strands (multi-fiber cables)',
        'Document with OTDR traces for each strand',
        'Record power meter reading for link loss',
        'Verify acceptance per TIA/EIA standards',
        'Verify acceptance per project specifications',
        'Check connector loss (<0.5dB typical)',
        'Check splice loss (<0.3dB typical)',
        'Verify total link loss per design',
        'Generate OTDR traces for documentation',
        'Compile power meter readings',
        'Create summary report using Fluke OptiFiber or equivalent',
      ]
    },
    {
      phase: 'Activation & Handoff',
      items: [
        'Coordinate with client IT for network equipment installation',
        'Install switches in racks',
        'Connect patch cords (switch to patch panel)',
        'Power up equipment',
        'Verify link lights on all connections',
        'Test link from workstation to switch',
        'Verify speed (1Gbps, 10Gbps)',
        'Test PoE (if applicable)',
        'Document active ports',
        'Mount WiFi access points per ceiling plan',
        'Connect access points to network',
        'Verify power (PoE)',
        'Coordinate with IT for AP configuration',
        'Test WiFi coverage (heat map)',
        'Conduct final walk-through',
        'Check random outlets',
        'Verify labels match documentation',
        'Check faceplate condition',
        'Review with client representative',
      ]
    },
    {
      phase: 'Closeout',
      items: [
        'Update floor plans with final outlet locations',
        'Create as-built riser diagram',
        'Create rack elevation drawings (with equipment)',
        'Compile cable run sheets',
        'Document labeling scheme',
        'Compile test results binder (digital and print)',
        'Gather all manufacturer cut sheets',
        'Compile warranty information',
        'Include maintenance recommendations',
        'Create spare parts list',
        'Provide emergency contact numbers',
        'Conduct client facility staff training',
        'Train IT department on system',
        'Train on tracing cables',
        'Train on patch panel usage',
        'Teach basic troubleshooting',
        'Obtain training sign-off sheet',
        'Register all components for warranty',
        'Provide warranty certificates',
        'Schedule 11-month walk-through',
        'Document warranty start dates',
        'Submit final invoice',
        'Include all approved change orders',
        'Obtain lien waivers',
        'Release retainage',
        'Submit final pay application',
      ]
    },
  ],

  // ─── LOW VOLTAGE: ACCESS CONTROL SYSTEM ──────────────────────────────────
  low_voltage_access_control: [
    {
      phase: 'Bidding & Estimating',
      items: [
        'Obtain architectural door schedule',
        'Review security drawings (if available)',
        'Identify door types (main entry, interior office, stairwell, mechanical)',
        'Note door construction (metal, wood, glass, storefront)',
        'Check frame types (hollow metal, aluminum, wood)',
        'Identify existing access control system (if retrofit)',
        'Review IT requirements (network, VLAN, PoE)',
        'Obtain site plans for exterior doors/gates',
        'Conduct site walk-through',
        'Verify each door location and type',
        'Check door swing direction (in/out, left/right)',
        'Measure frame dimensions for hardware fit',
        'Verify power availability at each door',
        'Check network connectivity options',
        'Identify pathway challenges (concrete, masonry)',
        'Note environmental conditions (outdoor, wet locations)',
        'Document existing hardware (if retrofit)',
        'Count interior office doors (wood/metal)',
        'Count exterior entrance doors (storefront/glass)',
        'Count stairwell doors (fire rated)',
        'Count mechanical/electrical room doors',
        'Count data center/server room doors',
        'Count parking gates/barriers',
        'Count elevator lobby doors (elevator control)',
        'List card reader types per door (prox, smart, biometric)',
        'Determine electric strike requirements (fail secure vs. fail safe)',
        'Determine magnetic lock requirements (with DPS)',
        'List door position switch requirements (recessed or surface)',
        'Identify REX requirements (motion sensor or push button)',
        'Calculate door controller board needs (at door or in panel)',
        'Size power supply (based on door count)',
        'Calculate wire and conduit requirements',
        'Select main head-end server (hardware or virtual)',
        'Determine software licenses (per door or concurrent)',
        'Assess database server need (separate or integrated)',
        'Size network panels/enclosures',
        'Calculate power distribution module requirements',
        'Assess UPS/battery backup needs',
        'Determine Ethernet switch requirements (PoE for readers)',
        'Calculate input/output board extenders',
        'Assess elevator control interface board needs',
        'Estimate rough-in labor per door (conduit, wire, backbox)',
        'Estimate trim-out labor per door (reader, strike, lock, DPS, REX)',
        'Estimate panel installation labor',
        'Estimate programming labor (head-end, panels, doors)',
        'Estimate testing and commissioning labor',
        'Estimate client training hours',
        'Obtain manufacturer pricing (Lenel, Genetec, Honeywell, Avigilon, Mercury)',
        'Get distributor quotes (typically 20-40% off list)',
        'Obtain hardware supplier quotes (HES, Securitron, Von Duprin, Schlage)',
        'Quote wire and cable costs (18/2, 22/4, 16/2)',
        'Quote conduit and boxes',
        'Quote firestop materials',
        'Coordinate subcontractor quotes (electrical, door hardware, drywall, paint, IT)',
        'Calculate material markup (15-25%)',
        'Calculate labor markup (20-30%)',
        'Include bond and insurance (2-3%)',
        'Add general conditions (5-10%)',
        'Add profit margin (8-15%)',
        'Add contingency reserve (5-10%)',
      ]
    },
    {
      phase: 'Material Procurement & Inventory',
      items: [
        'Order long lead items (head-end server 2-4 weeks)',
        'Order software licenses',
        'Order specialty readers (biometric, custom finish)',
        'Order custom door hardware (special electric strikes)',
        'Order elevator control boards (1-2 weeks)',
        'Create door hardware schedule (Excel)',
        'Assign unique hardware set per door type',
        'Order reader finish (black, white, stainless)',
        'Order strike finish (match existing)',
        'Verify voltage requirements (12VDC vs. 24VDC)',
        'Check UL ratings (fire door requirements)',
        'Order reader cable (18/4 or 22/6 shielded)',
        'Order lock power cable (16/2 or 18/2)',
        'Order DPS cable (22/2)',
        'Order REX cable (22/2 or 18/2)',
        'Order network cable (Cat6)',
        'Order panel-to-panel cable (fiber or Cat6)',
        'Order conduit (EMT, flex) per specifications',
        'Order backboxes (single-gang, 4SQ)',
        'Order conduit fittings and hardware',
        'Set up secured storage for equipment',
        'Organize materials by door number (kitting)',
        'Check-in all materials against purchase orders',
        'Bench test readers and boards before installation',
        'Update firmware before installation',
        'Track serial numbers (for warranty and programming)',
      ]
    },
    {
      phase: 'Pre-Construction & Coordination',
      items: [
        'Create door detail sheets for each door type',
        'Specify reader mounting height (typically 40-48")',
        'Define strike type and voltage per door',
        'Define DPS location and type',
        'Define REX location and type',
        'Create wiring diagram for each door',
        'Create panel elevation drawings',
        'Show enclosure layout in drawings',
        'Show board positions in enclosure',
        'Define power supply location',
        'Define battery placement',
        'Mark conduit entry locations',
        'Create riser diagram (network topology)',
        'Show panel-to-panel connections',
        'Show head-end connection',
        'Create cable matrix (door to panel assignments)',
        'Compile cut sheets for all equipment',
        'Include door hardware schedule',
        'Add shop drawings to submittal',
        'Submit to engineer/architect/owner',
        'Track approval status',
        'Incorporate reviewer comments',
        'Obtain approved submittals',
        'Meet with door hardware supplier',
        'Verify electric strike prep in frames',
        'Confirm magnetic lock mounting provisions',
        'Check fire rating requirements',
        'Coordinate delivery timing',
        'Meet with IT department',
        'Establish IP addressing scheme',
        'Get VLAN assignment for access control',
        'Verify PoE switch capacity (if powering readers)',
        'Review firewall rules for remote access',
        'Meet with electrical contractor',
        'Confirm power requirements for panels',
        'Coordinate conduit rough-in locations',
        'Discuss emergency power requirements',
        'Meet with GC',
        'Review door installation schedule',
        'Confirm ceiling access requirements',
        'Coordinate paint and finish schedule',
        'Check if access control permit required',
        'Get fire department approval (if doors are fire rated)',
        'Obtain building permit (if structural modifications)',
        'Check elevator permit requirement (if elevator control)',
      ]
    },
    {
      phase: 'Rough-In Phase',
      items: [
        'Run conduit from each door to panel (3/4" for multiple cables)',
        'Use 1/2" conduit for single reader cable',
        'Run conduit between panels (if multiple)',
        'Install pull boxes at long runs',
        'Install conduit to power sources',
        'Support conduit per code',
        'Cap ends to prevent debris entry',
        'Install backbox at reader locations (40-48" height)',
        'Use single-gang deep box for reader',
        'Use mud ring for drywall',
        'Use masonry box for concrete/masonry',
        'Use surface mount for storefront',
        'Install backbox at DPS locations',
        'Use recessed switch (drill frame rough-in)',
        'Use surface switch (single-gang box or mud ring)',
        'Install backbox at REX locations',
        'Mount motion detector in high corner',
        'Mount push button at 48" height',
        'Verify strike prep in frame',
        'Confirm conduit access to frame',
        'Pull reader cable (18/4 or 22/6)',
        'Pull lock cable (16/2 for power)',
        'Pull DPS cable (22/2)',
        'Pull REX cable (22/2)',
        'Pull network cable (Cat6 for IP readers)',
        'Label both ends of all cables immediately',
        'Leave slack at door (12-18")',
        'Leave slack at panel (10-15 ft)',
        'Bundle cables neatly',
        'Protect cables from damage',
        'Firestop all penetrations through rated walls',
        'Use intumescent putty or caulk',
        'Document firestopping with photos',
        'Label firestop locations',
      ]
    },
    {
      phase: 'Panel Installation',
      items: [
        'Mount backboard (3/4" plywood) if required',
        'Paint backboard (black or white)',
        'Install panel enclosure',
        'Level and secure enclosure',
        'Position at accessibility height (60-72" to top)',
        'Allow 30" clearance in front',
        'Install boards into enclosure',
        'Connect power supplies',
        'Wire AC input to terminal block',
        'Connect batteries (UPS or backup)',
        'Install grounding (to building ground)',
        'Dress internal wiring with tie wraps',
        'Label all internal components',
        'Pull field cables into enclosure',
        'Strip and prepare wire ends',
        'Terminate on correct input/output boards',
        'Terminate reader cables (Wiegand or OSDP)',
        'Terminate lock relay cables (COM, NO, NC)',
        'Terminate DPS input cables (zones)',
        'Terminate REX input cables (zones)',
        'Label each wire at termination point',
        'Document termination on as-built',
        'Leave service loops in enclosure',
        'Connect Ethernet cable to panel',
        'Terminate on network switch (if in panel)',
        'Note MAC address and IP assignment',
        'Test network connectivity',
      ]
    },
    {
      phase: 'Trim-Out: Door Hardware',
      items: [
        'Mount reader to backbox or surface',
        'Use gasket for outdoor/wet locations',
        'Connect power wires (red/black)',
        'Connect data wires (green/white)',
        'Connect LED control (if applicable)',
        'Connect tamper wires (if applicable)',
        'Secure reader with tamper-resistant screws',
        'Test reader LED (verify power)',
        'Verify electric strike fits frame prep',
        'Install strike into frame',
        'Connect power wires (16/2)',
        'Observe polarity (if DC)',
        'Use diode for back EMF suppression',
        'Test manual operation (latch engages)',
        'Adjust for proper fit (door closes freely)',
        'Mount magnetic lock on header or frame',
        'Mount armature on door',
        'Align precisely (no gap issues)',
        'Connect power (16/2)',
        'Use diode or suppressor',
        'Install integral door position switch',
        'Test hold force (door should not open)',
        'Install recessed DPS (drill into frame)',
        'Install surface DPS (mount on frame and door)',
        'Connect 22/2 wires (NO or NC)',
        'Adjust magnet alignment',
        'Test DPS with door open/closed',
        'Mount motion detector in corner above door',
        'Set detection pattern (avoid false triggers)',
        'Connect 22/2 (NO/NC/C)',
        'Adjust sensitivity',
        'Mount REX push button in single-gang box (48")',
        'Connect 18/2 or 22/2',
        'Install cover plate',
        'Test REX activation (door unlocks or signals)',
        'Coordinate with door closer adjustment',
        'Verify door closes properly after release',
        'Check fire door operation (closer speed)',
        'Test panic hardware (exit devices) function',
      ]
    },
    {
      phase: 'System Programming',
      items: [
        'Install server hardware or VM',
        'Install operating system (Windows Server)',
        'Install database (SQL Server)',
        'Install access control software',
        'Apply latest patches and updates',
        'Configure network settings (static IP)',
        'Set up backup schedule',
        'Configure panel IP addresses',
        'Test communication to head-end',
        'Update panel firmware (if needed)',
        'Synchronize time with server',
        'Create door objects in software',
        'Assign reader to each door',
        'Assign lock relay to each door',
        'Assign DPS input to each door',
        'Assign REX input to each door',
        'Set unlock time (typically 5-7 seconds)',
        'Set door held open time (typically 15-60 seconds)',
        'Set forced door time (immediate or delayed)',
        'Configure door lock modes (locked, unlocked, card only, card+PIN)',
        'Set reader type (prox, smart, biometric)',
        'Configure Wiegand format (26-bit, 34-bit, etc.)',
        'Set OSDP mode (if using secure communication)',
        'Configure reader LED behavior',
        'Set buzzer/tone settings',
        'Configure DPS as "Door Position Switch"',
        'Set NO/NC based on hardware',
        'Set debounce time (avoid false triggers)',
        'Configure REX as "Request to Exit"',
        'Set REX behavior (unlock door, shunt alarm)',
        'Configure lock relay (fail safe/fail secure)',
        'Set relay pulse time (for strikes)',
        'Create user database',
        'Import users (if HR system integration)',
        'Assign access levels (which doors, times)',
        'Assign validity dates (contractors, temps)',
        'Create card/PIN assignments',
        'Enroll biometric templates (if applicable)',
        'Create business hours schedule',
        'Create after-hours schedule',
        'Create holiday schedules',
        'Assign schedules to doors',
        'Set automatic unlock/lock times',
        'Configure forced door alarm',
        'Configure held open alarm',
        'Configure duress alarm (if supported)',
        'Configure tamper alarms',
        'Set alarm actions (email, pop-up, sound)',
        'Configure automatic report generation',
        'Set up email delivery of reports',
        'Create custom reports (as needed)',
      ]
    },
    {
      phase: 'Testing & Commissioning',
      items: [
        'Verify all doors connected and powered',
        'Check panel communication online',
        'Verify all inputs/outputs configured',
        'Test server communication',
        'Conduct card read test (valid card)',
        'Test card read test (invalid card)',
        'Test card read range (3-5" typical)',
        'Verify LED response (green for access)',
        'Test REX activation (door unlocks)',
        'Verify no alarm generated on REX',
        'Test DPS with door open',
        'Verify DPS restoral when closed',
        'Force door open and verify alarm',
        'Hold door open and verify alarm timeout',
        'Verify lock engage/disengage',
        'Check fail safe/fail secure operation',
        'Test manual override (key override)',
        'Test elevator floor access (if applicable)',
        'Test intercom integration (if applicable)',
        'Test video intercom release',
        'Test alarm monitoring (all alarm types)',
        'Test real-time event viewing',
        'Test report generation',
        'Test backup and restore',
        'Test failover (if redundant)',
        'Test battery backup (power loss)',
        'Simulate multiple card reads simultaneously',
        'Test database performance',
        'Verify panel can handle all doors',
        'Document test results per door',
        'Create system acceptance test report',
        'Get client sign-off sheet',
      ]
    },
    {
      phase: 'Integration Phase',
      items: [
        'Configure CCTV system integration',
        'Link cameras to doors',
        'Test video pop-up on card read',
        'Test video recording on alarm',
        'Configure active directory/LDAP integration',
        'Set up automatic user provisioning',
        'Test user sync',
        'Verify deactivated employees lose access',
        'Connect to lighting control',
        'Test access-triggered light activation',
        'Connect to HVAC',
        'Test occupied/unoccupied sequences',
        'Connect to visitor management system',
        'Test temporary credential creation',
        'Verify credential expiration works',
      ]
    },
    {
      phase: 'Training Phase',
      items: [
        'Train administrators on software navigation',
        'Train on user management (add, delete, modify)',
        'Train on access level assignment',
        'Train on report generation',
        'Train on alarm response',
        'Train on system backup procedures',
        'Train on troubleshooting common issues',
        'Provide administrator training manual',
        'Train operators on daily operations',
        'Train on manual unlock/lock',
        'Train on override functions',
        'Train on alarm acknowledgement',
        'Train on lost card procedures',
        'Train security on guard station operations',
        'Train on alarm response procedures',
        'Train on emergency unlock procedures',
        'Train on fire alarm integration (door release)',
        'Create quick reference guides',
        'Document emergency procedures',
        'Create emergency contact list',
        'Get training sign-off from client',
      ]
    },
    {
      phase: 'Closeout',
      items: [
        'Update door hardware schedule (as-built)',
        'Create as-built wiring diagrams per door',
        'Create panel wiring diagrams (as-built)',
        'Create as-built riser diagram',
        'Compile IP address schedule',
        'Create software configuration backup',
        'Provide customized user manual',
        'Gather manufacturer cut sheets',
        'Compile warranty information',
        'Create maintenance schedule documentation',
        'Create spare parts list',
        'Provide emergency contact numbers',
        'Register all equipment for warranty',
        'Provide warranty certificates',
        'Schedule 11-month walk-through',
        'Document warranty start dates',
        'Submit final invoice',
        'Include all approved change orders',
        'Obtain lien waivers',
        'Release retainage',
      ]
    },
  ],

  // ─── DEFAULT (generic) for types without a specific template ──────────────
  _default: [
    {
      phase: 'Bidding & Estimating',
      items: [
        'Review project documents and scope',
        'Perform quantity takeoff',
        'Obtain material pricing',
        'Estimate labor hours',
        'Prepare and submit bid',
      ]
    },
    {
      phase: 'Pre-Construction',
      items: [
        'Submit shop drawings',
        'Obtain permits',
        'Procure materials',
        'Schedule subcontractors',
      ]
    },
    {
      phase: 'Construction',
      items: [
        'Mobilize to site',
        'Complete rough-in work',
        'Complete trim-out',
        'Coordinate inspections',
      ]
    },
    {
      phase: 'Testing & Commissioning',
      items: [
        'Perform system testing',
        'Correct deficiencies',
        'Obtain inspection sign-off',
      ]
    },
    {
      phase: 'Closeout',
      items: [
        'Submit as-built drawings',
        'Provide O&M manuals',
        'Conduct owner training',
        'Submit final billing',
      ]
    },
  ],
};

export function getPhaseTemplate(projectType) {
  return PHASE_TEMPLATES[projectType] || PHASE_TEMPLATES._default;
}