import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Link } from 'react-router-dom';
import { createPageUrl } from '../utils';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ArrowLeft, Bot, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';

export default function BidDetail() {
  const urlParams = new URLSearchParams(window.location.search);
  const bidId = urlParams.get('id');
  const queryClient = useQueryClient();
  const [generating, setGenerating] = useState(false);

  const { data: bid } = useQuery({
    queryKey: ['bidOpportunity', bidId],
    queryFn: async () => {
      const bids = await base44.entities.BidOpportunity.filter({ id: bidId });
      return bids[0];
    },
    enabled: !!bidId
  });

  const { data: estimate } = useQuery({
    queryKey: ['bidEstimate', bidId],
    queryFn: async () => {
      const estimates = await base44.entities.BidEstimate.filter({ bid_opportunity_id: bidId });
      return estimates[0];
    },
    enabled: !!bidId
  });

  const generateEstimate = async () => {
    setGenerating(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Generate a detailed cost estimate for this low voltage project:

Title: ${bid.title}
Type: ${bid.project_type}
Scope: ${bid.scope_of_work}
Description: ${bid.description}

Generate line items with quantity, unit, unit cost, and total. Include labor estimate.`,
        response_json_schema: {
          type: "object",
          properties: {
            line_items: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: { type: "string" },
                  quantity: { type: "number" },
                  unit: { type: "string" },
                  unit_cost: { type: "number" },
                  total_cost: { type: "number" },
                  category: { type: "string" }
                }
              }
            },
            labor_hours: { type: "number" },
            labor_rate: { type: "number" }
          }
        }
      });

      const materialCost = result.line_items.reduce((sum, item) => sum + item.total_cost, 0);
      const laborCost = result.labor_hours * result.labor_rate;
      const subtotal = materialCost + laborCost;
      const total = subtotal * 1.35; // 15% overhead + 20% profit

      await base44.entities.BidEstimate.create({
        bid_opportunity_id: bidId,
        organization_id: bid.organization_id,
        ...result,
        material_cost: materialCost,
        labor_cost: laborCost,
        subtotal: subtotal,
        total_bid_amount: total
      });

      queryClient.invalidateQueries({ queryKey: ['bidEstimate'] });
      toast.success('Estimate generated by AI');
    } catch (error) {
      toast.error('Failed to generate estimate');
    } finally {
      setGenerating(false);
    }
  };

  if (!bid) return <div>Loading...</div>;

  return (
    <div className="space-y-6">
      <Link to={createPageUrl('BidOpportunities')} className="inline-flex items-center gap-2 text-slate-500 hover:text-slate-900">
        <ArrowLeft className="h-4 w-4" />
        Back to Bids
      </Link>

      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-semibold">{bid.title}</h1>
          <p className="text-slate-500">{bid.client_name}</p>
        </div>
        {!estimate && (
          <Button onClick={generateEstimate} disabled={generating}>
            <Bot className="h-4 w-4 mr-2" />
            {generating ? 'Generating...' : 'Generate Estimate with AI'}
          </Button>
        )}
      </div>

      <Tabs defaultValue="estimate" className="w-full">
        <TabsList>
          <TabsTrigger value="estimate">Estimate</TabsTrigger>
          <TabsTrigger value="details">Details</TabsTrigger>
        </TabsList>

        <TabsContent value="estimate" className="mt-6">
          {estimate ? (
            <EstimateView estimate={estimate} />
          ) : (
            <Card>
              <CardContent className="py-12 text-center">
                <p className="text-slate-500 mb-4">No estimate created yet</p>
                <Button onClick={generateEstimate} disabled={generating}>
                  <Bot className="h-4 w-4 mr-2" />
                  Generate with AI
                </Button>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="details">
          <Card>
            <CardHeader>
              <CardTitle>Project Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div><strong>Type:</strong> {bid.project_type}</div>
              <div><strong>Location:</strong> {bid.location}</div>
              <div><strong>Description:</strong> {bid.description}</div>
              <div><strong>Scope:</strong> {bid.scope_of_work}</div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function EstimateView({ estimate }) {
  const materialTotal = estimate.line_items?.reduce((sum, item) => sum + (item.total_cost || 0), 0) || 0;
  
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Line Items</CardTitle>
        </CardHeader>
        <CardContent>
          <table className="w-full text-sm">
            <thead className="border-b">
              <tr className="text-left">
                <th className="py-2">Description</th>
                <th>Qty</th>
                <th>Unit</th>
                <th>Unit Cost</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {estimate.line_items?.map((item, i) => (
                <tr key={i} className="border-b">
                  <td className="py-2">{item.description}</td>
                  <td>{item.quantity}</td>
                  <td>{item.unit}</td>
                  <td>${item.unit_cost?.toFixed(2)}</td>
                  <td>${item.total_cost?.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Summary</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <div className="flex justify-between"><span>Material Cost:</span><span>${materialTotal.toFixed(2)}</span></div>
          <div className="flex justify-between"><span>Labor ({estimate.labor_hours} hrs @ ${estimate.labor_rate}/hr):</span><span>${estimate.labor_cost?.toFixed(2)}</span></div>
          <div className="flex justify-between"><span>Subtotal:</span><span>${estimate.subtotal?.toFixed(2)}</span></div>
          <div className="flex justify-between"><span>Overhead ({estimate.overhead_percent}%):</span><span>${(estimate.subtotal * (estimate.overhead_percent / 100)).toFixed(2)}</span></div>
          <div className="flex justify-between"><span>Profit ({estimate.profit_margin_percent}%):</span><span>${(estimate.subtotal * (estimate.profit_margin_percent / 100)).toFixed(2)}</span></div>
          <div className="flex justify-between font-bold text-lg border-t pt-2">
            <span>Total Bid Amount:</span>
            <span className="text-green-600">${estimate.total_bid_amount?.toFixed(2)}</span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}