import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const templates = [
      // Contracts (10)
      { category: 'contracts', name: 'Subcontractor Agreement', description: 'Standard agreement for subcontractor engagement', content: 'This Subcontractor Agreement ("Agreement") is entered into as of [Date], between [Company Name] ("Contractor") and [Subcontractor Name] ("Subcontractor").\n\nSCOPE OF WORK:\n[Describe work to be performed]\n\nCOMPENSATION:\nTotal contract amount: $[Amount]\nPayment terms: [Terms]\n\nINSURANCE:\nSubcontractor shall maintain: General Liability ($2M), Workers Comp as required by law\n\nTERMS:\n- Work must commence: [Date]\n- Expected completion: [Date]\n- Change orders must be approved in writing' },
      { category: 'contracts', name: 'Change Order Form', description: 'Official change order template', content: 'CHANGE ORDER\n\nProject: [Project Name]\nDate: [Date]\nChange Order #: [Number]\n\nDESCRIPTION OF WORK:\n[Describe changes]\n\nREASON FOR CHANGE:\n[Reason]\n\nCOST IMPACT:\nOriginal Contract Amount: $[Amount]\nChange Order Amount: $[Amount]\nNew Contract Total: $[Amount]\n\nTIME IMPACT:\nOriginal Completion Date: [Date]\nTime Extension: [Days]\nNew Completion Date: [Date]\n\nSignatures:\n_________________  _________________ \nContractor         Subcontractor' },
      { category: 'contracts', name: 'Purchase Order Template', description: 'Standard PO for material orders', content: 'PURCHASE ORDER\n\nPO #: [Number]\nDate: [Date]\nProject: [Project Name]\n\nVENDOR INFORMATION:\nName: [Vendor Name]\nAddress: [Address]\nContact: [Contact Info]\n\nITEMS:\n1. [Item Description] - Qty: [Qty] - Unit Price: $[Price] - Total: $[Amount]\n2. [Item Description] - Qty: [Qty] - Unit Price: $[Price] - Total: $[Amount]\n\nSUBTOTAL: $[Amount]\nTAX (if applicable): $[Amount]\nSHIPPING: $[Amount]\nTOTAL: $[Amount]\n\nDelivery Address: [Address]\nRequired Delivery Date: [Date]\n\nTerms: [Net 30/Net 60]\nAuthorized by: [Name]' },
      { category: 'contracts', name: 'Equipment Rental Agreement', description: 'Rental terms for construction equipment', content: 'EQUIPMENT RENTAL AGREEMENT\n\nEquipment: [Equipment Type]\nModel: [Model]\nSerial #: [Serial #]\n\nRental Period:\nStart Date: [Date]\nEnd Date: [Date]\n\nRental Rate: $[Amount] per [day/week/month]\nTotal Rental Cost: $[Amount]\n\nRENTAL CONDITIONS:\n- Renter responsible for all fuel, maintenance, and damage\n- Equipment must be returned in same condition as received\n- Damage beyond normal wear subject to repair charges\n- Insurance required during rental period\n\nRETURN PROCEDURE:\n- Schedule return at least 5 days in advance\n- Equipment must be clean and operational\n- Late returns charged at daily rate\n\nSigned: _________________ Date: _________' },
      { category: 'contracts', name: 'Confidentiality Agreement', description: 'NDA for protecting project information', content: 'CONFIDENTIALITY AGREEMENT\n\nThis Agreement is between [Company Name] and [Party Name]\n\nCONFIDENTIAL INFORMATION:\nAll project plans, specifications, cost estimates, and business information are confidential.\n\nOBLIGATIONS:\n- Maintain strict confidentiality of all project information\n- Do not disclose to third parties without written permission\n- Return all documents upon project completion\n- Violation results in immediate termination and legal action\n\nEXCEPTIONS:\nPublicly available information is not covered by this agreement.\n\nDURATION:\nThis agreement remains in effect for 5 years from project completion.' },
      { category: 'contracts', name: 'Lien Waiver Form', description: 'Waiver of lien rights', content: 'CONDITIONAL LIEN WAIVER\n\nProject: [Project Name]\nPayment Period: [Date Range]\nAmount of Payment: $[Amount]\n\nI acknowledge receipt of $[Amount] for work and materials provided to the above project.\n\nIn exchange for payment, I hereby waive any right to file a lien or claim against the project property for work or materials provided during the payment period.\n\nThis waiver is conditional upon the check not being returned unpaid.\n\nSigned: _________________\nName (Print): _________________\nTitle: _________________\nCompany: _________________\nDate: _________________' },
      { category: 'contracts', name: 'Project Insurance Certificate', description: 'Insurance requirements documentation', content: 'PROJECT INSURANCE REQUIREMENTS\n\nProject: [Project Name]\nContractor: [Contractor Name]\nProject Manager: [PM Name]\n\nREQUIRED COVERAGE:\n1. General Liability: $2,000,000\n2. Workers Compensation: As required by state\n3. Equipment Insurance: Full replacement value\n4. Pollution Liability: $1,000,000 (if applicable)\n5. Builder\'s Risk: Full project cost\n\nCERTIFICATES:\n- Must name [Owner Name] as additional insured\n- Must be on file before work begins\n- Must remain in effect throughout project duration\n\nPOLICY DETAILS:\nInsurance Company: [Company]\nPolicy #: [Number]\nExpiration Date: [Date]\nAgent Contact: [Contact Info]' },
      { category: 'contracts', name: 'Work Authorization Form', description: 'Approval to begin work', content: 'WORK AUTHORIZATION\n\nAuthorization #: [Number]\nDate: [Date]\nProject: [Project Name]\n\nAUTHORIZED WORK:\n[Description of work]\n\nCONTRACTOR:\nName: [Name]\nCompany: [Company]\nContact: [Contact]\n\nAUTHORIZED BY:\nName: [PM Name]\nTitle: [Title]\nSignature: _________________ Date: _________\n\nWORK MUST BEGIN BY: [Date]\nWORK MUST COMPLETE BY: [Date]\n\nCONDITIONS:\n- All permits and insurance must be current\n- All safety protocols must be followed\n- Project manager approval required before any changes\n- Work may be halted if non-compliance observed' },
      { category: 'contracts', name: 'Contractor Onboarding Checklist', description: 'Required documents before work starts', content: 'CONTRACTOR ONBOARDING CHECKLIST\n\nContractor: [Name]\nProject: [Project Name]\nStart Date: [Date]\n\nREQUIRED DOCUMENTS:\n☐ Signed contract\n☐ Insurance certificates\n☐ Workers comp proof\n☐ General liability proof\n☐ W-9 or Tax form\n☐ ID/Background check\n☐ Safety training certification\n☐ Equipment list\n☐ Emergency contact info\n☐ Equipment insurance\n\nSAFETY REQUIREMENTS:\n☐ OSHA 10-hour card (if required)\n☐ Competency exam passed\n☐ Site safety orientation completed\n☐ PPE requirements acknowledged\n☐ Emergency procedures reviewed\n\nPROJECT INFORMATION:\n☐ Project plans reviewed\n☐ Site visit completed\n☐ Scope of work understood\n☐ Payment terms confirmed\n☐ Change order process explained\n\nCompleted by: _________________ Date: _________' },
      { category: 'contracts', name: 'Material Delivery Log', description: 'Track all material deliveries', content: 'MATERIAL DELIVERY LOG\n\nProject: [Project Name]\nPeriod: [Date Range]\n\nDELIVERY #1\nDate: [Date]\nVendor: [Vendor]\nItems: [Description]\nQuantity: [Qty]\nCondition: [Good/Damaged]\nReceived by: [Name]\nNotes: [Any issues]\n\nDELIVERY #2\nDate: [Date]\nVendor: [Vendor]\nItems: [Description]\nQuantity: [Qty]\nCondition: [Good/Damaged]\nReceived by: [Name]\nNotes: [Any issues]\n\n[Continue as needed]\n\nTOTAL DELIVERIES: [Number]\nANY SHORTAGES: [Yes/No]\nANY DAMAGE: [Yes/No]' },

      // Bid Forms (10)
      { category: 'bid_forms', name: 'Construction Bid Proposal', description: 'Comprehensive bid submission form', content: 'BID PROPOSAL\n\nProject Name: [Project Name]\nProject Location: [Location]\nBid Date: [Date]\nBid Due Date: [Date]\n\nBIDDER INFORMATION:\nCompany: [Company Name]\nAddress: [Address]\nLicense #: [Number]\nInsurance Status: [Current/Expired]\n\nPROJECT SCOPE:\n[Detailed scope of work]\n\nPROPOSED SCHEDULE:\nStart Date: [Date]\nCompletion Date: [Date]\nTotal Days: [Number]\n\nCOST BREAKDOWN:\nLabor: $[Amount]\nMaterials: $[Amount]\nEquipment: $[Amount]\nPermits/Inspections: $[Amount]\nContingency (5%): $[Amount]\nTOTAL BID: $[Amount]\n\nPAYMENT SCHEDULE:\n[Schedule details]\n\nCERTIFICATIONS:\n☐ Bonded and insured\n☐ Licensed and experienced\n☐ References available\n☐ Can meet schedule\n\nSigned: _________________ Date: _________' },
      { category: 'bid_forms', name: 'Request for Quote (RFQ)', description: 'Formal request for subcontractor bids', content: 'REQUEST FOR QUOTE (RFQ)\n\nProject: [Project Name]\nTrade: [Trade Type]\nIssue Date: [Date]\nDue Date: [Date]\nQuote #: [Number]\n\nSCOPE OF WORK:\n[Detailed description of work required]\n\nPROJECT REQUIREMENTS:\n- Location: [Address]\n- Timeline: [Start] to [End]\n- Quality Standards: [Standards]\n- Safety Requirements: [Requirements]\n- Insurance Required: [Details]\n\nDELIVERABLES:\n- Detailed cost estimate\n- Timeline/schedule\n- Material specifications\n- Crew composition\n- Insurance certificates\n- References\n\nQUOTE MUST INCLUDE:\n1. Labor costs\n2. Material costs\n3. Equipment costs\n4. Permits and fees\n5. Waste removal\n6. Contingency\n\nPLEASE RETURN TO:\n[Contact Name]\n[Email]\n[Phone]\n\nQuote is valid for: [30/60] days' },
      { category: 'bid_forms', name: 'Bid Summary Sheet', description: 'One-page bid comparison tool', content: 'BID SUMMARY SHEET\n\nProject: [Project Name]\nDate Prepared: [Date]\n\nBIDDER #1: [Name] | BIDDER #2: [Name] | BIDDER #3: [Name]\n\nBID PRICE:\nBidder 1: $[Amount] | Bidder 2: $[Amount] | Bidder 3: $[Amount]\n\nSCHEDULE:\nBidder 1: [Days] days | Bidder 2: [Days] days | Bidder 3: [Days] days\n\nLIENCE STATUS:\nBidder 1: ☐ Current | Bidder 2: ☐ Current | Bidder 3: ☐ Current\n\nINSURANCE:\nBidder 1: ☐ Current | Bidder 2: ☐ Current | Bidder 3: ☐ Current\n\nEXPERIENCE:\nBidder 1: [Years] years | Bidder 2: [Years] years | Bidder 3: [Years] years\n\nRECOMMENDATION:\nSelected Bidder: _________________ Reason: _________________\n\nApproved by: _________________ Date: _________' },
      { category: 'bid_forms', name: 'Equipment Cost Estimate', description: 'Equipment-specific bidding form', content: 'EQUIPMENT COST ESTIMATE\n\nProject: [Project Name]\nEstimate Date: [Date]\nEstimator: [Name]\n\nEQUIPMENT REQUIREMENTS:\n\n1. [Equipment Type]\n   Quantity: [Qty]\n   Rental Period: [Dates]\n   Daily Rate: $[Amount]\n   Subtotal: $[Amount]\n\n2. [Equipment Type]\n   Quantity: [Qty]\n   Rental Period: [Dates]\n   Daily Rate: $[Amount]\n   Subtotal: $[Amount]\n\n3. [Equipment Type]\n   Quantity: [Qty]\n   Rental Period: [Dates]\n   Daily Rate: $[Amount]\n   Subtotal: $[Amount]\n\nADDITIONAL COSTS:\nDelivery: $[Amount]\nPickup: $[Amount]\nOperator (if needed): $[Amount]\n\nTOTAL EQUIPMENT COST: $[Amount]\n\nNOTES:\n[Any special conditions or requirements]' },
      { category: 'bid_forms', name: 'Labor Rate Schedule', description: 'Prevailing wage and labor rate form', content: 'LABOR RATE SCHEDULE\n\nProject: [Project Name]\nEffective Date: [Date]\n\nTRADE/POSITION | HOURLY RATE | OT RATE | FRINGE BENEFITS\n\nForeman\n$[Amount] | $[Amount] | $[Amount]\n\nJourneyman [Trade]\n$[Amount] | $[Amount] | $[Amount]\n\nApprentice [Trade]\n$[Amount] | $[Amount] | $[Amount]\n\nLaborer\n$[Amount] | $[Amount] | $[Amount]\n\nOperator\n$[Amount] | $[Amount] | $[Amount]\n\nTotal Crew Rate: $[Amount]/hour\n\nFRINGE BENEFIT BREAKDOWN:\nHealth & Welfare: $[Amount]\nPension: $[Amount]\nTraining Fund: $[Amount]\n\nPREVAILING WAGE COMPLIANCE:\n☐ Meets prevailing wage requirements\n☐ Project location: [County]\n☐ Applicable rate: [Rate]\n\nAuthorized by: _________________ Date: _________' },
      { category: 'bid_forms', name: 'Materials Takeoff & Pricing', description: 'Material quantity and cost listing', content: 'MATERIALS TAKEOFF & PRICING\n\nProject: [Project Name]\nDate: [Date]\nTradesperson: [Name]\n\nMATERIAL QUANTITY | UNIT | UNIT COST | TOTAL COST\n\n[Material 1]\n[Qty] | [Unit] | $[Cost] | $[Total]\n\n[Material 2]\n[Qty] | [Unit] | $[Cost] | $[Total]\n\n[Material 3]\n[Qty] | [Unit] | $[Cost] | $[Total]\n\n[Material 4]\n[Qty] | [Unit] | $[Cost] | $[Total]\n\n[Material 5]\n[Qty] | [Unit] | $[Cost] | $[Total]\n\nSUBTOTAL: $[Amount]\nWaste Factor (10%): $[Amount]\nTAX (where applicable): $[Amount]\nTOTAL MATERIALS: $[Amount]\n\nVENDOR SOURCES:\n[Vendor 1]: $[Amount]\n[Vendor 2]: $[Amount]\n[Vendor 3]: $[Amount]\n\nRECOMMENDED VENDOR: [Vendor] - Best price and availability' },
      { category: 'bid_forms', name: 'Subcontractor Bid Analysis', description: 'Compare and evaluate subcontractor quotes', content: 'SUBCONTRACTOR BID ANALYSIS\n\nTrade: [Trade Name]\nProject: [Project Name]\nAnalysis Date: [Date]\n\nSUBCONTRACTOR #1: [Name]\nBid Amount: $[Amount]\nSchedule: [Days]\nExperience: [Years] years\nLicense Status: ☐ Current\nInsurance Status: ☐ Current\nReferences: [Number] available\nNegotiated Price: $[Amount]\n\nSUBCONTRACTOR #2: [Name]\nBid Amount: $[Amount]\nSchedule: [Days]\nExperience: [Years] years\nLicense Status: ☐ Current\nInsurance Status: ☐ Current\nReferences: [Number] available\nNegotiated Price: $[Amount]\n\nSUBCONTRACTOR #3: [Name]\nBid Amount: $[Amount]\nSchedule: [Days]\nExperience: [Years] years\nLicense Status: ☐ Current\nInsurance Status: ☐ Current\nReferences: [Number] available\nNegotiated Price: $[Amount]\n\nRECOMMENDATION:\nSelected: [Name]\nReasons: [Details]\nAuthorized by: _________________ Date: _________' },
      { category: 'bid_forms', name: 'Cost Estimate Template', description: 'Detailed construction cost estimate', content: 'DETAILED COST ESTIMATE\n\nProject: [Project Name]\nLocation: [Address]\nDate Prepared: [Date]\nEstimator: [Name]\n\nEXECUTIVE SUMMARY:\nProject Type: [Type]\nSize: [Sq Ft/Linear Ft]\nEstimated Cost: $[Amount]\nSchedule: [Days]\n\nCOST BREAKDOWN BY DIVISION:\n\n1. GENERAL CONDITIONS\n   Site Management: $[Amount]\n   Insurance & Bond: $[Amount]\n   Equipment (General): $[Amount]\n   Subtotal: $[Amount]\n\n2. SITE WORK\n   Demolition: $[Amount]\n   Grading: $[Amount]\n   Utilities: $[Amount]\n   Subtotal: $[Amount]\n\n3. STRUCTURAL\n   Foundation: $[Amount]\n   Framing: $[Amount]\n   Subtotal: $[Amount]\n\n4. MEP (MECHANICAL/ELECTRICAL/PLUMBING)\n   HVAC: $[Amount]\n   Electrical: $[Amount]\n   Plumbing: $[Amount]\n   Subtotal: $[Amount]\n\n5. FINISHES\n   Drywall: $[Amount]\n   Painting: $[Amount]\n   Flooring: $[Amount]\n   Subtotal: $[Amount]\n\nTOTAL PROJECT COST: $[Amount]\nContingency (5-10%): $[Amount]\nFINAL ESTIMATE: $[Amount]\n\nAssumptions: [List key assumptions]\nNotes: [Any special considerations]' },
      { category: 'bid_forms', name: 'Bid Scoring Matrix', description: 'Objective bid evaluation criteria', content: 'BID SCORING MATRIX\n\nProject: [Project Name]\nEvaluation Date: [Date]\n\nEVALUATION CRITERIA (Total Points: 100)\n\nCRITERIA | MAX POINTS | BIDDER 1 | BIDDER 2 | BIDDER 3\n\nPrice (30 points)\nLow bid gets 30, others proportional\n$[Amount]/30 | $[Amount]/30 | $[Amount]/30\n\nSchedule (20 points)\nShortest gets 20, others proportional\n[Days]/20 | [Days]/20 | [Days]/20\n\nQualifications (20 points)\n☐ Experience in similar projects\n☐ Licensed and insured\n☐ Safety record\n[Score]/20 | [Score]/20 | [Score]/20\n\nReferences (15 points)\n☐ 3+ quality references\n☐ Similar project types\n☐ Timely completion history\n[Score]/15 | [Score]/15 | [Score]/15\n\nFinancial Stability (10 points)\n☐ Established company\n☐ Good bonding capacity\n☐ Payment history\n[Score]/10 | [Score]/10 | [Score]/10\n\nTOTAL SCORE\n[Total]/100 | [Total]/100 | [Total]/100\n\nRECOMMENDED BIDDER: [Name] - Score: [Score]' },

      // Safety (10)
      { category: 'safety', name: 'Daily Safety Briefing Checklist', description: 'Daily safety meeting checklist', content: 'DAILY SAFETY BRIEFING\n\nProject: [Project Name]\nDate: [Date]\nLocation: [Area/Building]\nAttendees: [Number]\nConducted by: [Name]\n\nTOPICS COVERED:\n☐ Weather conditions and impacts\n☐ Current work activities for the day\n☐ Hazards specific to today\'s work\n☐ Personal protective equipment (PPE) requirements\n☐ Fall protection procedures\n☐ Equipment safety\n☐ Emergency procedures and locations\n☐ Near-miss or accident reports\n☐ OSHA regulations relevant to today\'s work\n☐ Site-specific hazards\n\nHAZARDS IDENTIFIED TODAY:\n1. [Hazard]: [Control measures]\n2. [Hazard]: [Control measures]\n3. [Hazard]: [Control measures]\n\nACTION ITEMS:\n[Action]: Assigned to: [Name] - Due: [Date]\n\nATTENDANCE SIGN-IN:\n[Name 1] | [Time] | [Signature]\n[Name 2] | [Time] | [Signature]\n[Name 3] | [Time] | [Signature]\n\nBriefing Leader Signature: _________________ Time: _________' },
      { category: 'safety', name: 'Near-Miss Report Form', description: 'Report potential safety incidents', content: 'NEAR-MISS INCIDENT REPORT\n\nProject: [Project Name]\nReport Date: [Date]\nIncident Date: [Date] Time: [Time]\n\nREPORTED BY:\nName: [Name]\nCompany: [Company]\nPosition: [Position]\nContact: [Contact]\n\nINCIDENT DETAILS:\nLocation: [Where it happened]\nDescription: [What happened]\nCould have resulted in: [Potential injury]\nWho could have been hurt: [Person/Position]\n\nROOT CAUSES:\n☐ Unsafe act\n☐ Unsafe condition\n☐ Lack of training\n☐ Equipment failure\n☐ Poor communication\n☐ Other: [Specify]\n\nCORRECTIVE ACTIONS TAKEN:\nAction 1: [Action] - By: [Name] - Date: [Date]\nAction 2: [Action] - By: [Name] - Date: [Date]\n\nPREVENTIVE MEASURES:\n[Measures to prevent recurrence]\n\nFOLLOW-UP:\n☐ Additional training needed\n☐ Equipment inspection required\n☐ Procedure revision needed\n☐ Management review required\n\nReport prepared by: _________________ Date: _________\nReviewed by Safety Officer: _________________ Date: _________' },
      { category: 'safety', name: 'Personal Protective Equipment (PPE) Log', description: 'Track PPE issuance and compliance', content: 'PPE ISSUANCE AND COMPLIANCE LOG\n\nProject: [Project Name]\nPeriod: [Date Range]\n\nEMPLOYEE | HARD HAT | SAFETY VEST | SAFETY GLASSES | GLOVES | BOOTS | RESPIRATOR | COMPLIANCE\n\n[Name] | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Yes\n[Name] | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Yes\n[Name] | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Yes\n[Name] | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Yes\n[Name] | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Issued | ☐ Yes\n\nPPE INSPECTION SCHEDULE:\nHard Hats: Inspect for cracks, every 30 days\nSafety Vests: Inspect stitching, monthly\nGlasses: Replace if scratched or damaged\nGloves: Replace as needed\nBoots: Replace as needed\nRespirators: Fit test annually\n\nNON-COMPLIANCE INCIDENTS:\nDate: [Date] | Employee: [Name] | Violation: [Details] | Action: [Corrective]\n\nMonitored by: _________________ Date: _________' },
      { category: 'safety', name: 'Hazard Assessment Form', description: 'Identify and assess job site hazards', content: 'JOB HAZARD ASSESSMENT\n\nProject: [Project Name]\nAssessment Date: [Date]\nAssessed by: [Name]\n\nTASK: [Description of work]\nLOCATION: [Area]\n\nSTEP-BY-STEP HAZARD IDENTIFICATION:\n\nStep 1: [Work activity]\nHazards identified: [Hazard 1], [Hazard 2]\nRisk Level: ☐ Low ☐ Medium ☐ High\nControls: [Control measures]\n\nStep 2: [Work activity]\nHazards identified: [Hazard 1], [Hazard 2]\nRisk Level: ☐ Low ☐ Medium ☐ High\nControls: [Control measures]\n\nStep 3: [Work activity]\nHazards identified: [Hazard 1], [Hazard 2]\nRisk Level: ☐ Low ☐ Medium ☐ High\nControls: [Control measures]\n\nCRITICAL HAZARDS:\n1. [Hazard]: [Why critical] - Control: [What prevents injury]\n2. [Hazard]: [Why critical] - Control: [What prevents injury]\n\nPERSONAL PROTECTIVE EQUIPMENT REQUIRED:\n☐ Hard hat ☐ Safety glasses ☐ Respirator\n☐ Safety vest ☐ Gloves ☐ Hearing protection\n☐ Safety boots ☐ Fall protection ☐ Other: [Specify]\n\nTRAINING REQUIRED:\n☐ Equipment operation\n☐ First aid\n☐ Fall protection\n☐ Confined space\n☐ Other: [Specify]\n\nReviewed by: _________________ Approved by: _________________' },
      { category: 'safety', name: 'Incident Investigation Report', description: 'Detailed accident investigation form', content: 'INCIDENT INVESTIGATION REPORT\n\nProject: [Project Name]\nIncident Date/Time: [Date] [Time]\nReport Date: [Date]\nInvestigator: [Name]\n\nINCIDENT DESCRIPTION:\nWhat happened: [Description]\nWhere it occurred: [Location]\nWho was involved: [Name/Position]\nWitnesses: [Names]\n\nINJURY DETAILS:\nType of injury: [Type]\nBody part(s) affected: [Parts]\nSeverity: ☐ First Aid ☐ Medical Treatment ☐ Hospitalized\nLost time: ☐ Yes ☐ No - Days: [Number]\n\nCONTRIBUTING FACTORS:\n☐ Human factors (fatigue, distraction, rushing)\n☐ Equipment failure\n☐ Environmental conditions\n☐ Inadequate training\n☐ Inadequate supervision\n☐ Unsafe work practices\n☐ Other: [Specify]\n\nROOT CAUSE ANALYSIS:\nDirect cause: [Cause]\nContributing factors: [Factors]\nUnderlying cause: [Root cause]\n\nCORRECTIVE ACTIONS:\n1. [Action] - Responsible: [Name] - Target date: [Date]\n2. [Action] - Responsible: [Name] - Target date: [Date]\n3. [Action] - Responsible: [Name] - Target date: [Date]\n\nPREVENTIVE MEASURES:\n[Measures to prevent similar incidents]\n\nInvestigator: _________________ Date: _________\nApproved by: _________________ Date: _________' },
      { category: 'safety', name: 'Safety Audit Checklist', description: 'Comprehensive site safety audit', content: 'SAFETY AUDIT CHECKLIST\n\nProject: [Project Name]\nAudit Date: [Date]\nAuditor: [Name]\nLocation Inspected: [Area]\n\nGENERAL SAFETY (Yes/No/N/A):\n☐ Emergency action plan posted\n☐ First aid kit accessible\n☐ Fire extinguishers available\n☐ Emergency contact numbers posted\n☐ Safety data sheets (SDS) available\n☐ Incident reporting procedures understood\n\nPERSONAL PROTECTIVE EQUIPMENT:\n☐ Hard hats in use\n☐ Safety glasses in use\n☐ Gloves available and used\n☐ Safety vests visible\n☐ Hearing protection where needed\n☐ Fall protection equipment in use\n☐ Respirators fit-tested\n\nWORK SITE CONDITIONS:\n☐ Work areas kept clean\n☐ Debris properly removed\n☐ Electrical cords grounded\n☐ Scaffolding properly erected\n☐ Ladders secured\n☐ Guardrails installed\n☐ Proper signage posted\n☐ Lighting adequate\n\nEQUIPMENT & MACHINERY:\n☐ Guards in place on equipment\n☐ Equipment properly maintained\n☐ Operators certified\n☐ No hazardous modifications\n\nFINDINGS:\nCritical (immediate action): [Items]\nMajor (within 7 days): [Items]\nMinor (corrective action): [Items]\n\nAuditor signature: _________________ Date: _________\nManagement response due: [Date]' },
      { category: 'safety', name: 'Confined Space Entry Permit', description: 'Authorization for confined space entry', content: 'CONFINED SPACE ENTRY PERMIT\n\nProject: [Project Name]\nDate: [Date] Time: [Time]\nLocation: [Confined space location]\nPermit #: [Number]\n\nSPACE CHARACTERISTICS:\n☐ Tank ☐ Vault ☐ Silo ☐ Tunnel ☐ Trench ☐ Other: [Specify]\nDimensions: [Dimensions]\nPurpose of entry: [Why entering]\n\nATMOSPHERIC TESTING (Before Entry):\nOxygen: ☐ 19.5-23.5% [%]\nLower Explosive Limit: ☐ <25% LEL [%]\nToxic Gas (specify): ☐ <IDLH [Level]\nCO Level: ☐ <35 ppm [ppm]\n\nPREPARATION:\n☐ Space purged/ventilated\n☐ Hazardous materials removed\n☐ Equipment tested\n☐ Rescue equipment available\n☐ Attendant briefed\n☐ Entrant trained\n\nPERSONNEL:\nAuthorized entrant(s): [Names]\nAtmospheric monitor: [Name]\nAttendant: [Name]\nRescue team: [Contact info]\n\nEQUIPMENT:\n☐ Self-contained breathing apparatus\n☐ Harness and lifeline\n☐ Retrieval tripod\n☐ Two-way communication\n\nAUTHORIZATION:\nIssued by: _________________ Time: _________\nExpires: [Time - max 8 hours]\n\nUpon completion, remove permit and post copy of results.' },
      { category: 'safety', name: 'Safety Training Record', description: 'Employee safety training documentation', content: 'SAFETY TRAINING RECORD\n\nEmployee Name: [Name]\nCompany: [Company]\nPosition: [Position]\nEmployee ID: [ID]\nHire Date: [Date]\n\nTRAINING HISTORY:\n\nCourse: OSHA 10-Hour Construction\nDate Completed: [Date]\nCertificate #: [Number]\nExpiration: [Date]\nProvider: [Provider]\nInstructor: [Name]\n\nCourse: Fall Protection\nDate Completed: [Date]\nCertificate #: [Number]\nExpiration: [Date]\nProvider: [Provider]\nInstructor: [Name]\n\nCourse: First Aid/CPR\nDate Completed: [Date]\nCertificate #: [Number]\nExpiration: [Date]\nProvider: [Provider]\nInstructor: [Name]\n\nCourse: Bloodborne Pathogens\nDate Completed: [Date]\nCertificate #: [Number]\nExpiration: [Date]\nProvider: [Provider]\nInstructor: [Name]\n\nCourse: Hazard Communication\nDate Completed: [Date]\nCertificate #: [Number]\nExpiration: [Date]\nProvider: [Provider]\nInstructor: [Name]\n\nCourse: Site-Specific Orientation\nDate Completed: [Date]\nProject: [Project Name]\nInstructor: [Name]\n\nUPCOMING TRAINING:\nCourse: [Course] - Scheduled: [Date]\nCourse: [Course] - Scheduled: [Date]\n\nCertifications Current: ☐ Yes ☐ No\nNext Review Date: [Date]\nMaintained by: _________________ Date: _________' },

      // Punch Lists (5)
      { category: 'punch_lists', name: 'Final Inspection Punch List', description: 'Items to be completed before final inspection', content: 'FINAL INSPECTION PUNCH LIST\n\nProject: [Project Name]\nInspection Date: [Date]\nContractor: [Name]\nProject Manager: [Name]\n\nITEM | LOCATION | DESCRIPTION | PRIORITY | STATUS | ASSIGNED TO | DUE DATE\n\n1 | [Location] | [Description] | ☐ High | ☐ Open | [Name] | [Date]\n2 | [Location] | [Description] | ☐ High | ☐ Open | [Name] | [Date]\n3 | [Location] | [Description] | ☐ Medium | ☐ Open | [Name] | [Date]\n4 | [Location] | [Description] | ☐ Medium | ☐ Open | [Name] | [Date]\n5 | [Location] | [Description] | ☐ Low | ☐ Open | [Name] | [Date]\n\nTOTAL ITEMS: [Number]\nHIGH PRIORITY: [Number]\nMEDIUM PRIORITY: [Number]\nLOW PRIORITY: [Number]\n\nNOTES:\n[Any special instructions or requirements]\n\nAll items must be completed by: [Date]\n\nPrepared by: _________________ Date: _________\nContractor acknowledgement: _________________ Date: _________' },
      { category: 'punch_lists', name: 'Weekly Progress Punch List', description: 'Track open items during construction', content: 'WEEKLY PROGRESS PUNCH LIST\n\nProject: [Project Name]\nWeek of: [Date]\nPhase: [Phase]\n\nOPEN ITEMS FROM PREVIOUS WEEK:\nItem 1 | Location | Status | Target Completion\nItem 2 | Location | Status | Target Completion\n\nNEW ITEMS THIS WEEK:\nItem 1 | Location | Reason | Priority\nItem 2 | Location | Reason | Priority\nItem 3 | Location | Reason | Priority\n\nCOMPLETED THIS WEEK:\nItem 1 | Location | Completion Date\nItem 2 | Location | Completion Date\nItem 3 | Location | Completion Date\nItem 4 | Location | Completion Date\n\nOUTSTANDING ITEMS:\nTotal Open: [Number]\nHigh Priority: [Number]\nMedium Priority: [Number]\nLow Priority: [Number]\n\nCONSTRAINTS:\n[Any blockers or issues affecting completion]\n\nNEXT WEEK FOCUS:\n[Items to prioritize next week]\n\nWeek prepared by: _________________ Date: _________' },
      { category: 'punch_lists', name: 'Deficiency Correction Log', description: 'Track corrections of deficiencies', content: 'DEFICIENCY CORRECTION LOG\n\nProject: [Project Name]\nStart Date: [Date]\n\nDEFICIENCY # | DESCRIPTION | LOCATION | IDENTIFIED | ASSIGNED TO | COMPLETION TARGET | ACTUAL DATE | VERIFIED\n\n001 | [Description] | [Location] | [Date] | [Name] | [Date] | [Date] | ☐ Yes\n002 | [Description] | [Location] | [Date] | [Name] | [Date] | [Date] | ☐ Yes\n003 | [Description] | [Location] | [Date] | [Name] | [Date] | [Date] | ☐ Yes\n004 | [Description] | [Location] | [Date] | [Name] | [Date] | [Date] | ☐ Yes\n005 | [Description] | [Location] | [Date] | [Name] | [Date] | [Date] | ☐ Yes\n\nSUMMARY:\nTotal deficiencies identified: [Number]\nCompleted: [Number]\nPending: [Number]\nOverdue: [Number]\n\nNOTES:\n[Any issues or concerns]\n\nLog maintained by: _________________ Date: _________' },
      { category: 'punch_lists', name: 'Final Close-Out Punch List', description: 'Items required for project closeout', content: 'FINAL CLOSE-OUT PUNCH LIST\n\nProject: [Project Name]\nCompletionDate Target: [Date]\nProject Manager: [Name]\n\nDOCUMENTATION REQUIRED:\n☐ As-built drawings complete and signed\n☐ All O&M manuals collected\n☐ Warranties collected and filed\n☐ Final inspections passed\n☐ Certificates of occupancy obtained\n☐ All permits closed out\n☐ Fire and life safety sign-off\n\nFINAL INSPECTIONS:\n☐ Building official\n☐ Fire marshal\n☐ Health department\n☐ Utility companies\n☐ Client final walkthrough\n\nCONTRACT CLOSEOUT:\n☐ Final payment submitted\n☐ Lien waivers received from all trades\n☐ Insurance certificates expired\n☐ Bonds released\n☐ Change orders finalized\n☐ Final accounting completed\n\nSITE CONDITIONS:\n☐ All temporary facilities removed\n☐ Site cleaned and cleared\n☐ Landscaping complete\n☐ Final grading complete\n\nHANDOVER:\n☐ Keys delivered\n☐ Access codes provided\n☐ System training completed\n☐ Operation manuals provided\n\nProject ready for final acceptance: ☐ Yes ☐ No\nDate ready: [Date]\n\nProject Manager signature: _________________ Date: _________\nClient acknowledgement: _________________ Date: _________' },

      // Continue with more templates...
      { category: 'daily_logs', name: 'Daily Construction Log', description: 'Document daily site activities', content: 'DAILY CONSTRUCTION LOG\n\nProject: [Project Name]\nDate: [Date]\nWeather: [Conditions]\nTemperature: [Temp]\n\nCREW ON SITE:\nTotal workers: [Number]\nTraffic: [Trade] - [Count] workers\n[Trade] - [Count] workers\n\nWORK PERFORMED:\n[Description of work completed]\n[Description of work completed]\n[Description of work completed]\n\nEQUIPMENT USED:\n[Equipment] - [Hours used]\n[Equipment] - [Hours used]\n\nMATERIALS DELIVERED:\n[Material] - [Quantity]\n[Material] - [Quantity]\n\nVISITORS:\nOwner: [Name] - [Time]\nInspectors: [Names] - [Time]\nOthers: [Names]\n\nINCIDENTS/ISSUES:\n☐ None ☐ Safety issue ☐ Equipment problem ☐ Delivery delayed\nDetails: [Details]\n\nSAFETY:\n☐ Daily safety briefing held\n☐ No incidents\n☐ All PPE in use\n☐ Site cleaned up\n\nLOG PREPARED BY: [Name] - SIGNATURE: _________________ TIME: _________' },
      { category: 'schedules', name: 'Critical Path Method (CPM) Schedule', description: 'Project scheduling template', content: 'PROJECT SCHEDULE - CRITICAL PATH METHOD\n\nProject: [Project Name]\nStart Date: [Date]\nCompletion Date: [Date]\nTotal Duration: [Days]\n\nMAJOR MILESTONES:\n- Project Kickoff: [Date]\n- Permit Approval: [Date]\n- Foundation Complete: [Date]\n- Rough-In Complete: [Date]\n- Final Inspection: [Date]\n- Occupancy: [Date]\n\nPHASE | DURATION | START | FINISH | FLOAT | CRITICAL\nSite Prep | [Days] | [Date] | [Date] | [Days] | ☐ Yes\nFoundation | [Days] | [Date] | [Date] | [Days] | ☐ Yes\nFraming | [Days] | [Date] | [Date] | [Days] | ☐ Yes\nMEP Rough-In | [Days] | [Date] | [Date] | [Days] | ☐ Yes\nInterior Finishes | [Days] | [Date] | [Date] | [Days] | ☐ Yes\nFinal Inspections | [Days] | [Date] | [Date] | [Days] | ☐ Yes\n\nDEPENDENCIES:\nFraming depends on: Foundation complete\nMEP depends on: Framing complete\nFinishes depend on: MEP complete\nInspections depend on: All work complete\n\nRESOURCE ALLOCATION:\nForeman: [Name] - [Dates]\nCarpenter: [Name] - [Dates]\nElectrician: [Name] - [Dates]\nPlumber: [Name] - [Dates]\n\nSchedule prepared by: _________________ Approved by: _________________' },
      { category: 'equipment_logs', name: 'Equipment Maintenance Log', description: 'Track equipment service and repairs', content: 'EQUIPMENT MAINTENANCE LOG\n\nEquipment: [Type]\nModel: [Model]\nSerial #: [Serial #]\nLocation: [Location]\nDaily Operator: [Name]\n\nMAINTENANCE SCHEDULE:\nDaily: Check fluids, filters, operation\nWeekly: Clean, inspect for damage\nMonthly: Service per manual\nAnnually: Full inspection and certification\n\nMaintenance Record:\nDATE | HOURS | WORK PERFORMED | PARTS USED | COST | TECHNICIAN | NOTES\n[Date] | [Hours] | [Work] | [Parts] | $[Cost] | [Name] | [Notes]\n[Date] | [Hours] | [Work] | [Parts] | $[Cost] | [Name] | [Notes]\n\nREPAIRS:\nDATE | ISSUE | REPAIR | COST | DOWN TIME | TECHNICIAN\n[Date] | [Issue] | [Repair] | $[Cost] | [Hours] | [Name]\n\nCERTIFICATIONS:\nLast Inspection: [Date]\nNext Due: [Date]\nStatus: ☐ Current ☐ Expired\n\nCumulative Cost: $[Amount]\nCumulative Hours: [Hours]\n\nMaintained by: _________________ Date: _________' },
      { category: 'rfi_forms', name: 'Request for Information (RFI)', description: 'Formal RFI submission form', content: 'REQUEST FOR INFORMATION (RFI)\n\nRFI #: [Number]\nDate Submitted: [Date]\nProject: [Project Name]\nSubmitted by: [Name/Company]\nSubmitted to: [Name/Company]\n\nSUBJECT: [Subject]\n\nDESCRIPTION:\n[Detailed description of question or information needed]\n\nRELATED DOCUMENTS:\n☐ Drawing reference: [Sheet/Detail]\n☐ Specification reference: [Section]\n☐ Contract reference: [Article]\n☐ Attached photos: [Yes/No]\n\nIMPACT:\n☐ Schedule impact: [Days]\n☐ Cost impact: $[Amount]\n☐ No anticipated impact\n\nRESPONSE REQUIRED BY: [Date]\n\nRESOLUTION (To be completed by A/E or PM):\n[Resolution or answer]\n\nRESPONCE DATE: [Date]\nRESPONDED BY: [Name/Title]\n\nCOPIES TO:\n☐ Project Manager\n☐ General Contractor\n☐ Architect\n☐ Engineers\n☐ Owner\n\nSubmitted by: _________________ Date: _________\nReceived by: _________________ Date: _________' },
      { category: 'submittals', name: 'Product Submittal Form', description: 'Submittal documentation for approval', content: 'PRODUCT SUBMITTAL\n\nProject: [Project Name]\nSubmittal #: [Number]\nDate Submitted: [Date]\nSubmitted by: [Contractor/Supplier]\n\nPRODUCT INFORMATION:\nProduct Name: [Name]\nManufacturer: [Manufacturer]\nModel #: [Number]\nSpecification Reference: [Section]\n\nDESCRIPTION:\n[Product description and specifications]\n\nJUSTIFICATION:\n[Why this product was selected]\n\nCOMPLIANCE:\n☐ Meets spec requirements\n☐ Approved equal\n☐ Cost savings\n☐ Performance improvement\n\nATTACHMENTS:\n☐ Product data sheets\n☐ Test reports/Certifications\n☐ Samples (attached)\n☐ Installation instructions\n☐ Warranty information\n☐ LEED documentation\n\nVENDOR INFORMATION:\nSupplier: [Company]\nContact: [Contact info]\nLead Time: [Days]\nAvailability: [Notes]\n\nAPPROVAL SECTION:\nComments: [Comments]\nStatus: ☐ Approved ☐ Approved as noted ☐ Rejected ☐ Resubmit\n\nApproved by: _________________ Title: _________________ Date: _________' },
      { category: 'inspection', name: 'Construction Inspection Report', description: 'Third-party inspection documentation', content: 'CONSTRUCTION INSPECTION REPORT\n\nProject: [Project Name]\nInspection Date: [Date]\nInspection Type: [Type - Framing/Electrical/Plumbing]\nInspector: [Name/Company]\nInspection Permit #: [Number]\n\nWORK INSPECTED:\n[Detailed description of work inspected]\n\nCODE COMPLIANCE:\n☐ Complies with plans and specs\n☐ Complies with building code\n☐ Complies with adopted standards\n☐ Non-compliant items noted\n\nCOMPLIANCE ISSUES:\n[List any code or specification violations]\n\nCORRECTIONS REQUIRED:\n1. [Issue]: [Correction needed]\n2. [Issue]: [Correction needed]\n3. [Issue]: [Correction needed]\n\nCORRECTION TIMELINE:\nCritical (immediate): [Date]\nMajor (within 5 days): [Date]\nMinor (within 14 days): [Date]\n\nRESCHEDULE INSPECTION:\nDate: [Date]\nTime: [Time]\nContact: [Contact]\n\nINSPECTION RESULT:\n☐ PASSED\n☐ CONDITIONAL PASS (with corrections)\n☐ FAILED - Resubmit\n\nInspector Signature: _________________ License #: _________________ Date: _________' },
      { category: 'closeout', name: 'Project Warranty Log', description: 'Track all product and system warranties', content: 'PROJECT WARRANTY LOG\n\nProject: [Project Name]\nCompletion Date: [Date]\n\nWARRANTY TRACKING:\n\nITEM | MANUFACTURER | WARRANTY PERIOD | EXPIRATION DATE | CERTIFICATE # | NOTES\n\nRoof | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\nHVAC Equipment | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\nElectrical | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\nPlumbing | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\nWindows/Doors | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\nFlooring | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\nPaint | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\nAppliances | [Manufacturer] | [Years] | [Date] | [#] | [Notes]\n\nWARRANTY UPDATES REQUIRED:\nDate | Item | Action | Assigned To | Due Date\n[Date] | [Item] | [Action] | [Name] | [Date]\n\nWARRANTY CLAIMS:\nDate | Item | Issue | Claim Filed | Approval Status\n[Date] | [Item] | [Issue] | [Date] | [Status]\n\nDOCUMENT STORAGE:\n☐ All warranties filed with owner\n☐ Digital copies retained\n☐ Hard copies organized by trade\n☐ Owner briefed on warranty process\n\nLog maintained by: _________________ Date: _________' },
      { category: 'changeorders', name: 'Formal Change Order', description: 'Official document for project changes', content: 'CHANGE ORDER\n\nProject: [Project Name]\nChange Order #: [Number]\nDate: [Date]\nOriginal Contract Date: [Date]\n\nCONTRACT PARTIES:\nOwner: [Name]\nContractor: [Name]\nArchitect/PM: [Name]\n\nDESCRIPTION OF CHANGE:\n[Detailed description of scope change]\n\nREASON FOR CHANGE:\n☐ Owner request\n☐ Design error/omission\n☐ Unforeseen condition\n☐ Value engineering\n☐ Other: [Specify]\n\nCONTRACT MODIFICATION:\n\nOriginal Contract Amount: $[Amount]\nPrevious Change Orders: +$[Amount]\nCurrent Contract Total: $[Amount]\n\nThis Change Order Amount: +/-$[Amount]\nNEW TOTAL CONTRACT AMOUNT: $[Amount]\n\nSCHEDULE MODIFICATION:\nOriginal Completion Date: [Date]\nTime Extension/(Reduction): (+/-)[Days]\nNEW COMPLETION DATE: [Date]\n\nAPPROVALS:\nOwner: _________________ Date: _________\nContractor: _________________ Date: _________\nArchitect/PM: _________________ Date: _________\n\nThis change order becomes effective upon execution by all parties.' }
    ];

    // Create templates in batches
    const batchSize = 10;
    let createdCount = 0;

    for (let i = 0; i < templates.length; i += batchSize) {
      const batch = templates.slice(i, i + batchSize);
      await Promise.all(
        batch.map(template => base44.entities.TemplateLibrary.create(template))
      );
      createdCount += batch.length;
    }

    return Response.json({
      success: true,
      templatesCreated: createdCount,
      message: `Successfully created ${createdCount} construction templates`
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});